### ISSUE TITLE
Supertest failing on SSL/HTTPS

### ISSUE THREAD

**Issue by EverettQuebral** [visionmedia/supertest#111]
this is what I'm getting when I'm trying to hit a box with a self signed certificate for testing

Error: 140735125684608:error:140773F2:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert unexpected message:../deps/openssl/openssl/ssl/s23_clnt.c:741:

**Comment by jy95** [comment]
Check this : 

```sh
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```

http://stackoverflow.com/questions/22654479/nodejs-https-api-testing-with-mocha-and-super-test-depth-zero-self-signed-cert
