### ISSUE TITLE
Optionally print response body/text on failure

### ISSUE THREAD

**Issue by timoxley** [visionmedia/supertest#12]
If I get a wrong status code back from a controller, it'd be nice if supertest had an optional 'print response body on failure' mode so I can see the content of the message associated with that wrong status code. Currently you have to go in and manually add additional debugging into like: `.expect(200, function() { console.log(arguments); done(); })` every time a test starts failing.

Another option might be to be smarter about generating the Error response in supertest, e.g. parsing the res.body and (optionally) jamming that into the error message. It could even somehow do some specialcase handling of the default connect error handler to populate the stack trace (if that's even possible).

**Comment by thedug** [comment]
+1

**Comment by mikalai-sauchanka** [comment]
+1. Some default option to enable failed requests logging would be very helpful

**Comment by sabrehagen** [comment]
+1 please!!

**Comment by paambaati** [comment]
+1. Or can someone show us how to console.log when `.expect(statusCode)` fails?

**Comment by sabrehagen** [comment]
I literally can't believe this essential feature hasn't been implemented. i'll add a pull request for it. the overhead of not having it is too great.

**Comment by lblazecki** [comment]
+1

**Comment by mindeavor** [comment]
I need this constantly. It's especially bad when a test seems to only fail sometimes.

**Comment by anoff** [comment]
If anyone stumbles upon this and wonders how to log at all. Appending this to your test case logs if an error occurs and rethrows the error via done.
```javascript
        .end((err, res) => {
          if (err) {
            console.error(res.error);
          }
          done(err);
        });
```

**Comment by Ctesias** [comment]
What if I'm using promises?  Putting something like this in the `catch` block only gives me the generic error that isn't helpful.  I can't call `.end` when using promises.

**Comment by strujillojr** [comment]
If anyone is still looking for a way to do this with Promises here's how I did it. According to the readme, "Expectations are run in the order of definition.", so I just created an expection before the `expect(statusCode)` that checks if the res is the correct statusCode, and if not prints out the body.

For example:
```
request(server)
  .get(endpoint)
  .query(query)
  .set('Accept', 'application/json; charsaet=utf-8')
  .expect(function(res) {
    if(res.status != statusCode){
      console.log(JSON.stringify(res.body, null, 2));
     }
  })
  .expect(statusCode);
```

**Comment by andygock** [comment]
I was looking for a solution to the same problem, and ended up making a VS Code snippet that would insert the following one-liner in my chain, for status code 204, as an example:

```
.expect((res) => (res.status != 204 ? console.log(res.body) : 0))
```

Similar to @strujillojr's suggestion. My response body is already a JSON payload.

**Comment by rhyek** [comment]
If you want something reusable, this what I did which is inspired by C# extension methods:
```typescript
import supertest from 'supertest';

(supertest as any).Test.prototype.expectOrPrint = function (
  this: supertest.Test,
  statusCode: number
) {
  this.expect((res) => {
    if (res.status !== statusCode) {
      console.error(JSON.stringify(res.body, null, 2));
    }
  });
  this.expect(statusCode);
  return this;
};

declare module 'supertest' {
  interface Test {
    expectOrPrint: (statusCode: number) => Test;
  }
}

```

and then you can use it like this:
```typescript
await request
  .post('/api/v1/graphql')
  .send({
    query: `{
      contacts(
        first: 1
      ) {
        id, firstName
      }
    }`,
  })
  .expectOrPrint(401);
```

**Comment by rhyek** [comment]
Actually, one problem with that solution (and previous solutions mentioned) is that the response body is not printed along-side the expect failure. Depending on how many tests there are and/or how many of those are failing, it's quite difficult to find the corresponding response body. I made the following modification which essentially replaces `expect`:

```typescript
import supertest from 'supertest';
import status from 'statuses';

(supertest as any).Test.prototype.expect = function (
  this: supertest.Test,
  statusCode: number
) {
  this.then((res) => {
    if (res.status !== statusCode) {
      let message = `expected ${statusCode} "${status(statusCode)}", got ${res.status} "${status(res.status)}"
response: ${JSON.stringify(res.body, null, 2)}`;
      throw message;
    }
  });
  return this;
};
```
With this, doing a normal `.expect(402)` would print out something like the following:

![image](https://user-images.githubusercontent.com/702922/94708285-a8fdfb80-0301-11eb-811c-cc7ff13a971e.png)

**Comment by FINDarkside** [comment]
Solition by @rhyek doesn't seem to work for me. All tests fill pass even if status codes do not match. Modified to following:
```Typescript
import supertest from 'supertest';
import status from 'statuses';

(supertest as any).Test.prototype.expect = function (
  this: supertest.Test,
  statusCode: number
) {
  return this.then((res) => {
    if (res.status !== statusCode) {
      const message = `expected ${statusCode} "${status(statusCode)}", got ${res.status} "${status(res.status)}" 
response: ${JSON.stringify(res.body, null, 2)}`;
      throw message;
    }
    return this;
  });
};
```

**Comment by andrewtran1995** [comment]
I found the above solutions limiting in terms of allowing chained `expect` calls, so I found an alternative that alters the `assert` method on the prototype instead, s.t. you are effectively hard-coding the `end` logic.
```ts
import supertest from 'supertest';

declare module 'supertest' {
  interface Test {
    _assert(this: supertest.Test, resError: Error, res: supertest.Response, fn: Function)
  }
}

Object.defineProperties((supertest as any).Test.prototype, {
  '_assert': {
    value: (supertest as any).Test.prototype.assert,
  },
  'assert': {
    value: function (this: supertest.Test, resError, res, _fn) {
      // Hard-code the "end" function to print response information on error.
      this._assert(resError, res, (err, res) => {
        if (err) {
          throw new Error(`${err.message}\nstatus: ${res.status}\nresponse: ${JSON.stringify(res.body, null, 2)}`);
        }
      });
    }
  }
});
```
The advantage of this approach is:
* The ability to chain calls as normal (e.g., multiple `expect` calls).
* Not needing to overwrite or rewrite the existing `expect` assertion logic.
The disadvantage is the inability to use `end`. However, if you were already using promises, this should be a non-issue.

This results in error messages such as the following, which is output from a test that failed a response body checker.
```
Error: expect(received).toInclude(expected)

Expected string to include:
  "GraphQL is stopping"
Received:
  "GraphQL is running development server."
status: 200
response: {
  "data": {
    "hello": "GraphQL is running development server."
  }
}
```

**Comment by andrewtran1995** [comment]
I found the above solutions limiting in terms of allowing chained `expect` calls, so I found an alternative that alters the `assert` method on the prototype instead.
```ts
import supertest from 'supertest';

declare module 'supertest' {
  interface Test {
    _assert(this: supertest.Test, resError: Error, res: supertest.Response, fn: Function)
  }
}

Object.defineProperties((supertest as any).Test.prototype, {
  '_assert': {
    value: (supertest as any).Test.prototype.assert,
  },
  'assert': {
    value: function (this: supertest.Test, resError, res, fn) {
      this._assert(resError, res, (err, res) => {
        if (err) {
          throw new Error(`${err.message}\nstatus: ${res.status}\nresponse: ${JSON.stringify(res.body, null, 2)}`);
        }
        fn.call(this, err, res);
      });
    }
  }
});
```
This approach has the advantages of:
* The ability to chain calls as normal (e.g., multiple `expect` calls).
* Not needing to overwrite or rewrite the existing `expect` assertion logic.

This results in error messages such as the following, which is output from a test that failed a response body checker.
```
Error: expect(received).toInclude(expected)

Expected string to include:
  "GraphQL is stopping"
Received:
  "GraphQL is running development server."
status: 200
response: {
  "data": {
    "hello": "GraphQL is running development server."
  }
}
```
All-in-all, I'd still love some ability to configure `supertest` to allow for automatic response printing on error.

**Comment by yunicz** [comment]
solution proposed by @andrewtran1995 wasn't working for us so we decided to use following snippet

```
Object.defineProperties((supertest as any).Test.prototype, {
  '_assertStatus': {
    value: function (this: supertest.Test, status, res) {
      if (res.status !== status) {
        const a = http.STATUS_CODES[status];
        const b = http.STATUS_CODES[res.status];
        return new Error(`expected ${status} "${a}", got ${res.status} "${b}" \nresponse: ${JSON.stringify(res.body, null, 2)}`);
      }
    }
  }
});
```

**Comment by rluvaton** [comment]
solution proposed by @andrewtran1995 wasn't working for me either and after debugging I found out that the error stack trace was being logged, so just needed to replace the message from the stack  and it work!



```ts
import supertest from 'supertest';


declare module 'supertest' {

  interface Test {

    _assert(this: supertest.Test, resError: Error, res: supertest.Response, fn: Function)

  }

}



Object.defineProperties((supertest as any).Test.prototype, {

  '_assert': {

    value: (supertest as any).Test.prototype.assert,

  },

  'assert': {

    value: function (this: supertest.Test, resError, res, fn) {

      this._assert(resError, res, (err, res) => {

        if (err) {
          const originalMessage = err.message;

          err.message = `${err.message}\nstatus: ${res.status}\nresponse: ${JSON.stringify(res.body, null, 2)}`;
          err.stack = err.stack?.replace(originalMessage, err.message);

        }

        fn.call(this, err, res);

      });

    }

  }

});

```

**Comment by lucagiove** [comment]
I'd like a feature like this as well.
ReactTesting library does something similar with screen.debug() https://testing-library.com/docs/queries/about#screendebug

**Comment by mujdatdinc** [comment]
Here is what I use. This one also corrects stack trace.
```
 .expect(result(201));

function result(status: number): request.CallbackHandler {
  const s = new Error().stack.split('\n');
  s.splice(1, 1);

  return (err: any, res: request.Response) => {
    if ((res?.status || err.status) != status) {
      const e = new Error(
        `Expected ${status} ,got ${res?.status || err.status} resp: ${
          res?.body ? JSON.stringify(res.body) : err.text
        }`,
      );
      e.stack = e.stack
        .split('\n')
        .splice(0, 1) 
        .concat(s) // Remove this line not to show stack trace
        .join('\n');
      throw e;
    }
  };
```
![image](https://user-images.githubusercontent.com/9706932/160579051-7b7ba1bd-a86e-4ff8-8b3f-71a928e904ac.png)
