### ISSUE TITLE
Browserify support to match superagent

### ISSUE THREAD

**Issue by bevacqua** [visionmedia/supertest#122]
Are there any plans to match `superagent` in the browser? That way I would be able to write tests for HTTP in the server and XMLHttpRequest in the browser seamlessly.

The actual requests already work across the stack thanks to recent changes to `superagent`, but the mocking structure for the browser isn't there yet. So.

> Are there any plans to match `superagent` in the browser?

**Comment by SystemParadox** [comment]
+1

**Comment by begizi** [comment]
+1

**Comment by builtbylane** [comment]
+1

**Comment by deefactorial** [comment]
+1, if it did I could perform integration tests based on unit tests. I guess I will have to rewrite all the tests to use superagent instead.

**Comment by danthareja** [comment]
+1

**Comment by yoshuawuyts** [comment]
fwiw, I use [`nets`](https://github.com/maxogden/nets) nowadays which is both simpler & does play ball with `browserify`.
