### ISSUE TITLE
Unable to receive a octet stream

### ISSUE THREAD

**Issue by katcipis** [visionmedia/supertest#124]
Hi,

I was testing a web service that streams data that is received from a spawned process to the client. Everything was going fine, but suddenly, the tests started to fail intermittently (i loosed the "repeatable" property of my tests:-(), actually almost all the time it succeeded. 

Doing a little more debugging i was able to isolate the problem here:

https://gitorious.org/katcipis-playground/playground/source/5198249525f740af4a8507ae237aaf369777fe73:javascript/nodejs/supertest-streamed-response-problem

As can be seem on the streamed-response-tests.js, i just send a response on express using multiple writes, and when im done with it...i call end.

As expected...it works... but if you run the script load-test.sh, you can see that it will inevitably fail after some time repeating the same test:

```
  1) Streaming data test should send all chunks correctly:

      AssertionError: expected 1029 to equal 1031
      + expected - actual

      +1031
      -1029
```

It seems that some part of the data is not completely sent sometimes (or received), the amount of bytes missing is variable and the error sometimes happens very fast, on other cases it takes some time to happen.

Some stuff on the code (like random generation of the buffers) that seems a little weird is because this is a isolated fragment of the real test that i have failing, with this level of isolation it really seems o be a problem on the send/receive of the data.

Anyone has an idea if this is a bug or if I'm doing something wrong on the code ?

**Comment by isaachinman** [comment]
I have an image upload endpoint in my API that accepts `application/octet-stream` requests and handles these streams. I'd like to write test coverage for this endpoint but cannot figure out how to use supertest to stream an image.

Here's my code so far:

    const testImage = `${__dirname}/../../../assets/test_image.jpg`

    describe('Upload endpoint', () => {

      test('Successfully uploads jpg image', async () =>
        request(app)
          .post(`${ROOT_URL}${endpoints.add_image.route}`)
          .set('Authorization', `Bearer ${process.env.testUserJWT}`)
          .set('content-type', 'application/octet-stream')
          .pipe(fs.createWriteStream(testImage))
          .on('finish', (something) => {
            console.log(something)
          }))

    })

This code produces nothing, the `finish` event is never called, nothing is console logged, and this test suite actually passes as nothing is expected. I cannot chain a `.expect` onto this request, otherwise I get this runtime error:

> TypeError: (0 , _supertest2.default)(...).post(...).set(...).set(...).pipe(...).expect is not a function

How is such a thing accomplished?
