### ISSUE TITLE
cannot add CA to request 

### ISSUE THREAD

**Issue by MiroRadenovic** [visionmedia/supertest#136]
looking at: 
https://github.com/visionmedia/superagent/blob/master/test/node/https.js
is see that superagent supports providing the CA during the request

```
  request
      .get('https://localhost:8443/')
      .ca(cert)
```

but this is not possible in supertest

```
var requestHttps = require('supertest')('https://localhost:8002');
  requestHttps
                .get('/')
                .ca(fs.readFileSync('test/data/SSL/dev-client.crt'))
```

returns 
TypeError: Object #<Test> has no method 'ca'

Maybe i'm missing something, but to me this could be bug.

**Comment by drewish** [comment]
Is there a way to pass in an HTTP server and the CA cert?
```
  var agent = request.agent(server);
  agent.get('/').ca(caRootCertificate);
```
gets me a `TypeError: Object #<Test> has no method 'ca'`

**Comment by DMJ92** [comment]
I am getting below error
"fs.readFileSync is not a function error" 
what could be an issue?
