### ISSUE TITLE
Feature: chaining

### ISSUE THREAD

**Issue by hunterloftis** [visionmedia/supertest#14]
It would be awesome to be able to do this:

``` javascript
request(app)
  .get('/signin')
  .expect(200)
  .post('/signin')
  .send({ user: 'foo', pass: 'bar' })
  .expect(200)
  // ...etc...
```

**Comment by piranna** [comment]
Has there been any improvement regarding chaining? I'm having a similar code than @tj and I think it would be useful to be able to chain requests if you need to do several of them without needed to check for failure for each of them but instead doing so globally... :-/
