### ISSUE TITLE
Koa support

### ISSUE THREAD

**Issue by ahri** [visionmedia/supertest#149]
The express support is really nice; being able to run against an app without fixing up a webserver. Could we get this functionality for koa?

**Comment by fritx** [comment]
```plain
TypeError: app.address is not a function
      at Test.serverAddress (E:\dev\gtfo\node_modules\supertest\lib\test.js:55:1
8)
      at new Test (E:\dev\gtfo\node_modules\supertest\lib\test.js:36:12)
```

Using supertest@1.2.0 with koa@1.2.0.
Do I have to pass in `app.listen()`?

**Comment by mikelax** [comment]
@fritx  can you give that a try, that worked in the example above for the other user.

**Comment by fritx** [comment]
@mikelax yeah it works, but I'm wondering if supertest could improve in this case.
