### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by myndzi** [visionmedia/supertest#160]
Two things, really.

One: assertions are not thrown first-come first-served. If I have:

```
return request(app)
    .post('/api/sites')
    .send(site)
    .expect(201)
    .expect('Location', new RegExp('/api/site/\\d+'))
    .end()
```

And my app returns a 400 error, it fails on the 'Location' header, even though the `.expect(201)` method is called first. If I remove the `.expect('Location', ...)` method call, it does fail on 201 !== 400.

Truth be told, I'd rather have the HTTP status code checked before any headers, since it's a "higher level", but manual ordering in the source gives more control.

Secondly, if a body is available, it would be nice to report the body contents, at least optionally or on error conditions, since that can provide details as to _why_ the request failed.

**Comment by glenjamin** [comment]
I've just run this this too, using the following expectation:

```js
.expect(200, {
    view: 'steps/two',
    data: {
        step: 'two'
    }
}, done);
```

In error scenarios this gives me:      `Error: expected 404 "Not Found", got 400 "Bad Request"`, which isn't massively useful.

**Comment by maldimirov** [comment]
+1 for printing the body on status code expectation fail.
Right now I use supertest only for status and header assertions and Jest for body checking. The only way to check why a request has failed is to try/catch/log the script being tested.

**Comment by kjarmicki** [comment]
I was having the same issue with insufficient debugging information on failing status assertions, so I made a minimal plugin to capture and enhance errors: https://github.com/kjarmicki/supertest-capture-error
It should give you enough flexibility to decorate assertion errors with valuable info.
