### ISSUE TITLE
Enhancement: add support for .retry(n)

### ISSUE THREAD

**Issue by gollygeewizard** [visionmedia/supertest#167]
In a perfect world, there would be no ECONREST or ENOTFOUND, or 504, but in the real-world, especially when performing functional/integration tests while another team might be running load tests on a shared test environment, it would be really helpful to not bail at the first sign of trouble.

This enhancement request is for the addition of a '.retry(n)' request option.

i.e.

```
request(http://mydomain.com)
    .post('something_wonderful')
    .set('User-Agent', 'tester-testtown-testington')
    .send(data)
    .retry(3)
    .end(function(error, res) {

      if (error) throw error;
      callback(null, res);
    });
```

**Comment by tauren** [comment]
:+1:

**Comment by eexit** [comment]
Hello,

Any update on this ticket? 

Thanks,

**Comment by zabawaba99** [comment]
Quick note - I was able to get plugins to work by requiring superagent beforehand and applying the plugins before requiring supertest

```javascript
const superagent = require('superagent');
require('superagent-retry')(superagent);

const supertest = require('supertest');
```

**Comment by pszabop** [comment]
@zabawaba99 alas this workaround does not work for the module `superagent-use`.  Which is the module I need.  Ugh.

**Comment by nhnicwaller** [comment]
Was this issue closed because there are no plans to add retry support for supertest?
