### ISSUE TITLE
Extending Object prototype breaks supertest

### ISSUE THREAD

**Issue by nover** [visionmedia/supertest#174]
Hi,

I have some extensions on my Object prototype to make things easier and prettier for me in the code. It goes something along the lines:

```
if(!Object.prototype.toArray)
{
    /**
     * Converts the current object instance into an array
     * @returns {Array} An array of the object values
     */
    Object.prototype.toArray = function(){
        var arr = [];

        for(var key in this) {
            if (this.hasOwnProperty(key)) {
                arr.push(this[key]);
            }
        }
        return arr;
    }
}
```

Then, when issuing the most basic "test" via supertest:
```
var superagent = require('superagent');
var agent = superagent.agent();
....
request
        .get('/somepath')
        .end(function (err, res) {
            if (err) {
                throw err;
            }        
            done();
        });
```

I'm getting the error: 
"expected "toArray" header field".

Why on earth is supertest converting my extension methods into header field assertions? I cant seem to find anything regarding this in the documentation.

**Comment by jonathanong** [comment]
we're not going to support arbitrarily extending native prototypes...
