### ISSUE TITLE
Supertest fails on Content-Type

### ISSUE THREAD

**Issue by ilanbiala** [visionmedia/supertest#187]
Supertest says the content-type is text/plain, but when I use Postman or Chrome devtools and check the network tab, it correctly shows the content-type as text/html.

```
describe('Core controller unit tests:', function() {
	before(function(done) {
		request = request('http://localhost:3001');

		done();
	});

	describe('Loading the homepage', function() {
		it('should return 200 from GET /', function(done) {
			request
				.get('/')
				.expect('Content-Type', /html/)
				.expect(200, done);
		});
	});

	after(function(done) {
		done();
	});
});
```

**Comment by ilanbiala** [comment]
@gjohnson this still doesn't work for me..I'm positive my content-type is correct, can you take a look at this?

**Comment by ilanbiala** [comment]
@gjohnson when using an API tester like the Postman Chrome app, I get the content-type as text/html, so what is going on exactly?

**Comment by trainiac** [comment]
+1 always getting  "text/html; charset=utf-8" no matter what I do.

```js
    it('should respond with a 200 if the posted body is valid', function(done) {
        request(app)
            .post('/user/', {
                json: true,
                body: helpers.getUser()
            })
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(function(response) {
                debugger;
                response.res.json.id.should.eql('123');
            })
            .expect(200)
            .end(done);
    });

app.post('/user/', validate({body: helpers.getUserSchema()}), function(req, res) {
   res.set('Content-Type', 'applicaton/json'); 
   res.json({
        id: '1234'
    });
});
```

**Comment by rajrsingh** [comment]
same here

**Comment by ilanbiala** [comment]
@gjohnson any status on this?

**Comment by shiwtin** [comment]
@ilanbiala not sure it will help, maybe you should try setting the accept header of your supertest request.
```javascript
    request(app)
            .get('/')
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200, done);
```

**Comment by mikelax** [comment]
@ilanbiala can you attach the sample Postman request and response (with headers) that is working for your example? Is there some server redirect that is happening with the requests as that could change the response types. 
We use expect Content-Type in almost all our tests and it works for json, html, etc.

**Comment by mikelax** [comment]
Hi all, I don't think there is anything wrong with supertest, or superagent. 
Here is a quick test file I wrote that shows things working as they should for a basic express set up. 

```javascript
var request = require('supertest')
  , express = require('express');

var app = express();

app.post('/user/json', function(req, res) {
   res.set('Content-Type', 'application/json');
   res.json({
        id: '1234'
    });
});

app.post('/user/html', function(req, res) {
   res.set('Content-Type', 'text/html');
   res.send('id: 1234');
});


describe('POST /user/json', function(){
    it('should respond with a json 200 response setting Accept header', function(done) {
        request(app)
            .post('/user/json', {
                json: true,
                body: '{"id":"100","name":"Mike"}'
            })
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200)
            .end(done);
    });
    it('should respond with a json 200 not setting Accept header', function(done) {
        request(app)
            .post('/user/json', {
                json: true,
                body: '{"id":"100","name":"Mike"}'
            })
            .expect('Content-Type', /json/)
            .expect(200)
            .end(done);
    });
});

describe('POST /user/html', function(){
    it('should respond with an html 200 response setting Accept header', function(done) {
        request(app)
            .post('/user/html', {
                json: true,
                body: '{"id":"100","name":"Mike"}'
            })
            .set('Accept', 'application/json')
            .expect('Content-Type', /html/)
            .expect(200)
            .end(done);
    });
    it('should respond with an html 200 not setting Accept header', function(done) {
        request(app)
            .post('/user/html', {
                json: true,
                body: '{"id":"100","name":"Mike"}'
            })
            .expect('Content-Type', /html/)
            .expect(200)
            .end(done);
    });
});
```

**Comment by danielmihai** [comment]
Does supertest match Content-Type: application/json; charset=/whichevercharset/ with .expect('Content-Type', /json/) ? 

What should I write to make it do it ?

**Comment by mikelax** [comment]
@danielmihai  yes if you pass a regex as the second argument to .expect it will match in your example. 

ie:  
```.expect('Content-Type', /json/) ``` will match ```application/json; charset=utf-8```

**Comment by TeemuKoivisto** [comment]
Just FYI for other dummies like me whose tests failed on ```.expect("Content-Type", /json/)```

My mistake was refactoring this bit of code from 
```
res.status(statusCode).send(err); // err is an object
```
to
```
res.status(statusCode).send(message); // string from the err object
```
When the correct way would be
```
res.status(statusCode).send({ message, });
```


By default if the data is not inside curly brackets it will be rendered as html, not json. And the reason why I couldn't see it with Postman was because it still sends err-objects while in development environment, not test. Every day I relearn something new...

**Comment by cbt2016** [comment]
`request(app)
          .get('/')
          .expect('Content-Type','text/html; charset=utf-8')
          .end(done);
        
    });
`
while work perfectly whereas 
`request(app)
          .get('/')
          .expect('Content-Type','text/html')
          .end(done);
        
    });` 
won't work because the http header received adds an encoding of utf-8

**Comment by danielmihai** [comment]
You could use a regexp to match your expected content type. /text\/html/
would pass your test.

**Comment by LeoLiu1209** [comment]
it is work to return as json~
```javascript
describe('Loading the homepage', function() {  
      it('should return 200 from GET /', function(done) {  
            request  
            .get('/')  
            .set('Content-Type', 'application/json')  
            .expect(200, done);  
       });  
});
```

**Comment by akotranza** [comment]
Had this error in an older project using https://www.npmjs.com/package/express-force-https ... not a very popular package, but it will cause Express to always return 302 with html/text when using Supertest. With the tests expecting Content-Type of /json/ of course. Easy fix was to not use this package in test env. Commenting here in the off chance it saves someone else several hours of googling and debugging.

**Comment by PA55ION** [comment]
@LeoLiu1209 Thank you. Your solution works perfectly for me. I've to comment out `.expect('Content-Type', /json/)` and the test run smoothly but when I deleted the line that I 've commented out the test failed. Why is that? I'm a newbie.

`describe('POST /api', function() {
  it('responds with json', function(done) {
    request(app)
      .post('/api')
      .send({url: 'https://google.com'})
      .set('Content-Type', 'application/json')
      // .expect('Content-Type', /json/)
      .expect(200)
      .end(function(err, res) {
        if (err) return done(err);
        done();
      });
  });
});`

**Comment by Jetlum** [comment]
Had the same problem. Just need a little bit of code refactoring.

What solved the problem for me was:
Didn't pass: 
`notesRouter.get('/', (request, response) => {
	response.send('<h1>Hello World!</h1>')
})`

Passed:
`notesRouter.get('/', (request, response) => {
  const message = '<h1>Hello World</h1>'
	response.json({message})
})`

**Comment by Felexonyango** [comment]
Same error any help please 
describe('GET /api/auth/:id',()=>{
  
  it('should return user by id in database',async()=> {

    const id = 2
   const res = await app.get(`/api/auth/${id}`)

 
  res.should.have.a('object')

    
  })

})


  1) JOB
       GET api/job/:id
         should return  post by id:
     Uncaught AssertionError: expected 'text/html; charset=utf-8' to include 'application/json'
      at /home/felex/DevCon/test/jobs.test.js:74:21
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:716:12)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:916:18)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Felexonyango** [comment]
I'm getting error on testing .Any help please

**Comment by krzywiecki** [comment]
Thanks @mikelax! 

```
.post('/campaignunits/1/tvschedule', {
                json: true,
                body: '{ data: "test" }'
            })
            .set('Accept', 'application/json')
```

works without any errors.
