### ISSUE TITLE
post(url, data) does not send any data

### ISSUE THREAD

**Issue by SystemParadox** [visionmedia/supertest#189]
superagent allows the following syntax:

```
request(app).post('/url', { foo: 'bar' })
```

This should set the content-type to json and send the JSON data in the request body.

With supertest the above syntax results in no content-type and no body.

testcase:

```
  it('.post should work with data', function (done) {
    var app = express();

    app.use(express.bodyParser());

    app.post('/', function(req, res){
      res.send(req.body.name);
    });

    request(app)
    .post('/', { name: 'tobi' })
    .expect('tobi', done);
  })
```

Thanks.

**Comment by gabeio** [comment]
use:
```
it('.post should work with data', function (done) {
    var app = express();

    app.use(express.bodyParser());

    app.post('/', function(req, res){
      res.send(req.body.name);
    });

    request(app)
    .post('/')
    .send({ name: 'tobi' })
    .expect('tobi', done);
  })
```

**Comment by mikker** [comment]
Adding `.type('form')` fixed this for me.

**Comment by jonny2779** [comment]
+1 Mikker.

**Comment by fernandoPalaciosGit** [comment]
Thanks a lot, mayby fix the Accept POST Header

```javascript
         testServer
                    .post('/api/book/save/')
                    .type('form')
                    .send(data.book)
                    .set('Accept', /application\/json/)
                    .expect(201)
                    .end(function (err, res) { done(); });
```

**Comment by muneermuhammed** [comment]
Can we attach image file along with the same request without changing the type ?

**Comment by montaro** [comment]
This worked for me
```
import bodyParser from 'body-parser';
app.use(bodyParser.json());
```

**Comment by muneermuhammed** [comment]
+1 Montaro

**Comment by snackycracky** [comment]
+1 Montaro

**Comment by fritx** [comment]
Seems the readme has only this example, which can be very confusing.
Related: #168

```js
request(app)
.post('/')
.field('name', 'my awesome avatar')
.attach('avatar', 'test/fixtures/homeboy.jpg')
...
```

**Comment by fritx** [comment]
I didn't know there is another method:

```js
request(app)
  .post('/api/book/save/')
  .type('form')
  .send(data.book)
  .set('Accept', /application\/json/)
  .expect(201)
  .end(function (err, res) { done(); });
```

**Comment by zanemcca** [comment]
+1

**Comment by akanshgulati** [comment]
@fritx @zanemcca I don`t know how relevant is to see the help from this library for the supertest. But you can try using the documentation from it. 
http://unirest.io/nodejs.html

**Comment by WwupengP** [comment]
Adding .type('form') fixed my problem too

**Comment by omar-meshaal** [comment]
adding these two lines solves this problem
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

**Comment by RaisonBlue** [comment]
Be sure you're not looking for ` .query(postData)` instead of `.send(postData)`

**Comment by calidion** [comment]
it should use form as the default type instead of json.
where forms are standard http requests while jsons are file format.

**Comment by samueljseay** [comment]
I'm having trouble with a basic `post` with json body not coming through in Express 4.16.3 which has the body parsing stuff for json built in.

**Comment by mikelax** [comment]
@samueljseay as a heads up expressjs version 4 and above does *not* include body parsing middleware. See the [migration guide](https://expressjs.com/en/guide/migrating-4.html). You must use  a separate middleware library like [body-parser](https://www.npmjs.com/package/body-parser).

**Comment by olegario96** [comment]
> This worked for me
> 
> ```
> import bodyParser from 'body-parser';
> app.use(bodyParser.json());
> ```

Nowadays you should use `express.json()`, since `bodyParser`  is currently deprecated.

**Comment by gsanikidze** [comment]
I want send multipart/form-data and `req.body` is always empty object.

`test('multipart/form-data', async (done) => {
  const app = express();

  app.use(express.json());

  app.post('/', (req, res) => {
    console.log(req.body); // logs empty object -> {}

    done();
    return res.send();
  });

  await request(app)
    .post('/')
    .field('some', 'field')
    .attach('some_file', fs.readFileSync(`${__dirname}/index.ts`), { filename: 'some_file_name' });
});`

node=14.16.1
express=4.17.1
supertes=6.1.3
