### ISSUE TITLE
Percent-encoding

### ISSUE THREAD

**Issue by booxood** [visionmedia/supertest#207]
When have same query params, will convert to percent-encoding.

e.g.
```
var should = require('should');
var app = require('../../index');
var request = require('supertest').agent(app.listen());

it('get /v1/?a=1&a=2', function() {
  request.get('/v1/?a=1&a=2').end();
})
```

Server will received request ` GET /v1/?a%5B0%5D=1&a%5B1%5D=2`.

Expect received 'GET /v1/?a=1&a=2', how can don't convert?

**Comment by booxood** [comment]
I found the problem.

`supertest` depend on `superagent` version too lower.

In `superagent` latest version already improved. [code see here](https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L816)

Hope can follow up.

**Comment by mikelax** [comment]
Resolved in [PR 203](https://github.com/visionmedia/supertest/pull/203).
