### ISSUE TITLE
MAINTAINER

### ISSUE THREAD

**Issue by jonathanong** [visionmedia/supertest#208]
if anyone would like to maintain this library, speak up!

**Comment by defunctzombie** [comment]
Bueller

**Comment by mikelax** [comment]
I would be interested in stepping up to offer organizational support to the project. 
I'm not the strongest in javascript, but certainly can help in terms of organizing PRs, grouping issues into releases, and help keeping the libs updated. As long as there is someone else to help with technical js questions and bounce questions off of that should be fine.

**Comment by mikelax** [comment]
Anyone else that wants to help please speak up but I'm closing this ticket.
