### ISSUE TITLE
When sending request in JSON format strings in JSON come to server not in utf-8 format

### ISSUE THREAD

**Issue by PainKKKiller** [visionmedia/supertest#210]
I do this request:

``` javascript
var query = { interests: "кино вино", sender: 111111 };
            request(app)
            .post('/api/user/search/1?viewer_id=111111')
            .set('Content-Length', Buffer.byteLength(JSON.stringify(query)))
            .set('Accept', 'application/json')
            .expect(200)
            .send(query)
            .end(function (err, res) {
                if (err)
                    return done(err);
                should.not.exist(err);
                console.log(res.body);
                console.log(res.body.length);
                done();
            });
```

On my server-side in console I'm getting  { interests: "?????????", sender: 111111 } When doing this request with postman everything OK. It's really strange because JSON.stringify converts objects to utf-8 string.

**Comment by mikelax** [comment]
Does it work if you specify the Content-Type HTTP header with your POST?
ie. try adding:
```javascript
.set('Content-type', 'application/json; charset=utf-8')
```

**Comment by PainKKKiller** [comment]
No, it didn't help.

**Comment by mikelax** [comment]
hmm, what POST type are you doing in Postman, x-www-form-urlencoded? Can you generate the preview and paste it here?
You could also try: 
```javascript
.set('Content-Type', 'application/x-www-form-urlencoded')
```
This is the header that Postman most likely is using for your request.

**Comment by PainKKKiller** [comment]
Here is screenshot of my postman request. https://www.dropbox.com/s/81wimm52nc1rimx/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-05-06%2015.07.21.png?dl=0  
May be the thing is that I entered json as raw. Changing header to 'Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8' did nothing.
