### ISSUE TITLE
Question: Code Coverage

### ISSUE THREAD

**Issue by kylehotchkiss** [visionmedia/supertest#213]
probably a silly ? but have you or has anybody had luck with code coverage tests against the api server with this?

**Comment by sammyisseyegh** [comment]
I've just started playing with istanbul. Although I haven't tested any very complicated routes, I have with some basic ones, and istanbul seems smart enough to follow everything correctly :)

https://github.com/gotwarlost/istanbul

**Comment by kylehotchkiss** [comment]
I've been trying to get blanketjs to run w/ mocha+supertest but it says no SLOC or files :(  I was worried it was decoupling the server too much to actually see the files, but you say Istanbul is working here? Any config to post?

**Comment by mikelax** [comment]
Closing this ticket, this is out of scope for supertest.
