### ISSUE TITLE
supertest doesn't respect HTTP_PROXY environment variable.

### ISSUE THREAD

**Issue by MichaelJCole** [visionmedia/supertest#214]
Linux uses [http_proxy environment variables](http://www.cyberciti.biz/faq/linux-unix-set-proxy-environment-variable/) to proxy http requests through the command line.

```
# Proxy sees this request
http_proxy="http://127.0.0.1:8888" wget http://localhost:8000/somethingelse  
```

The request module respects these variables

```
// request.js
require('request').get('http://localhost:8000/myapi/'+ Math.random());
```

```
# Proxy sees this request
http_proxy="http://127.0.0.1:8888" node request.js 
```

Supertest either doesn't respect these variables (or I can't figure it out)

```
# Proxy doesn't see this requests
http_proxy="http://127.0.0.1:8888" ./node_modules/mocha/bin/mocha app.e2e.js
```

In my tests `console.log(process.env.http_proxy);` prints out the proxy configuration.

I've invested effort in supertest e2e tests.  I would like to record those tests through a proxy so I can replay them for a performance test.

Any suggestions?

Edit: There is a dependency issue with: https://github.com/TooTallNate/superagent-proxy
Edit2: This is possible to do with [Hippie](https://github.com/vesln/hippie), if you [use the latest version of request](https://github.com/MichaelJCole/hippie).

**Comment by MichaelJCole** [comment]
Here is a version of superagent that proxies:  https://github.com/TooTallNate/superagent-proxy

**Comment by mikelax** [comment]
Have you looked to see if superagent respects this env variable? That lib is used under the hood to make the requests. I will also try to spend some time researching to see if this is possible.

**Comment by cristian-smocot** [comment]
Until the problem with the proxy in **supertest** is resolved, I've used the following code with **superagent** and **superagent-proxy**

```javascript
var chai      = require('chai'),
	expect    = chai.expect,
	request   = require('superagent');

require('superagent-proxy')(request);

describe('Suite one . superagent-proxy', function() {

	var url, proxy;

	before(function() {
		url = 'http://www.google.ro/';
		proxy = process.env.http_proxy || 'http://user:password@proxy.com:8080';
	});

	it(' should test if google.ro responds', function(done) {

		request .get(url)
                .proxy(proxy)
                .set('Accept', 'text/html')
                .end(function(error, response) {
					expect(response).to.exist;
					expect(response.status).to.equal(200);
					done();
				});
	});
});
```

**Comment by MichaelJCole** [comment]
This issue may be helpful:
https://github.com/TooTallNate/superagent-proxy/issues/13#issuecomment-103306694

On Thu, May 28, 2015 at 9:33 AM, Cristian Smocot <notifications@github.com>
wrote:

> Until the problem with the proxy in *supertest* is resolved, I've used
> the following code with *superagent* and *superagent-proxy*
>
> var chai      = require('chai'),
>     expect    = chai.expect,
>     request   = require('superagent');
> require('superagent-proxy')(request);
>
> describe('Suite one . superagent-proxy', function() {
>
>     var url, proxy;
>
>     before(function() {
>         url = 'http://www.google.ro/';
>         proxy = process.env.http_proxy || 'http://user:password@proxy.com:8080';
>     });
>
>     it(' should test if google.ro responds', function(done) {
>
>         request .get(url)
>                 .proxy(proxy)
>                 .set('Accept', 'text/html')
>                 .end(function(error, response) {
>                     expect(response).to.exist;
>                     expect(response.status).to.equal(200);
>                     done();
>                 });
>     });
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/visionmedia/supertest/issues/214#issuecomment-106357991>
> .
>



-- 
Michael Cole
http://Powma.com

**Comment by markbjerke** [comment]
Looks like supertest doesn't expose the superagent.Request class so superagent-proxy can't decorate the prototype with it's proxy method. It would be trivial to change the code so the Request class was exposed.  I can't use this without proxy support.

**Comment by peidong-hu** [comment]
I got the same problem to correctly setup http_proxy to run test

**Comment by 01x01** [comment]
any solution with that? we are using the supertest for api testing . and we don't want to replace it to superagent! any solution for proxy?

**Comment by tauheedkhan** [comment]
use this https://www.npmjs.com/package/supertest-with-proxy
