### ISSUE TITLE
Add ES6 support

### ISSUE THREAD

**Issue by rkmax** [visionmedia/supertest#215]

**Comment by foxgaocn** [comment]
what I did is create a test_helper.js:
 
````
import sinon from 'sinon'
import chai from 'chai'
import sinonChai from 'sinon-chai'
var expect = chai.expect
chai.use(sinonChai)

var supertest = require("supertest");

module.exports = {
  sinon: sinon,
  chai: chai,
  expect: expect,
  supertest: supertest
} 
````
Then in your testing file:
````
import {sinon, chai, expect, supertest} from '../TestHelper'
````

**Comment by rkmax** [comment]
thanks @foxgaocn I'll using that. I dont know if this issue can remaind open until that supertest add ES6 support without using workarounds

**Comment by edenworky** [comment]
Any updates on this?

**Comment by mega6382** [comment]
Any updates on this?

**Comment by Iar0** [comment]
why this has been closed? 

I was able to use it with `import * as request from 'supertest';` but with the ts esModuleInterop to true `import request from 'supertest';` does not work, giving `TypeError: request is not a function`

**Comment by KostyaTretyak** [comment]
> For now I'm doing `import * as request =  require('supertest');` so I get also the type definitions.

Perhaps you wanted to write such an import:

```ts
import request =  require('supertest');
```

Yes?
