### ISSUE TITLE
Query String as Array

### ISSUE THREAD

**Issue by jtwebman** [visionmedia/supertest#216]
I am writing a test where I want to pass multiple values into the same query string item to make it an array. I am using the connects library that likes me add [] to the end and makes sure it is an array on the server side. If I pass just one like this:

```javascript
request(app)
    .get('/balance_records/?types[]=BalanceCredit')
```
Supertest does the correct thing and doesn't add anything to the url

But if I pass mutiple like this:

```javascript
request(app)
    .get('/balance_records/?types[]=BalanceCredit&types[]=BalanceDebit')
```

Supertest injects array elements like so:

/api/v1/accounts/1-VzLqGc7vJK/balance_records/?types%5B%5D[0]=BalanceCredit&types%5B%5D[1]=BalanceDebit

What I need is:
/api/v1/accounts/1-VzLqGc7vJK/balance_records/?types%5B%5D=BalanceCredit&types%5B%5D=BalanceDebit

Is there a way to turn this off or remove it. I not sure it is good practice to change the URL that I told you to go to. I would say including url encoding it. Maybe I want to test bad url characters.

**Comment by jtwebman** [comment]
Actually I move this over the superagent because it is an issue with it not this library.

**Comment by jtwebman** [comment]
I am re-open this because after much research the superagent library has already fixed this issue. The issue is the because in the package file for supertest you have "supertagent": "~1.0.0". Well they are on version 1.2 and looks like maybe the don't have any 1.0.* release so it is pulling the 0.21.0 release which is way behind. You guys need to ether set it to "supertagent": "~1.2.0" or "supertagent": "^1.0.0" to fix this.

**Comment by mikelax** [comment]
This issue has been resolved in [PR 203](https://github.com/visionmedia/supertest/pull/203)
We will be releasing version 1.0.0 of supertest containing this fix very soon.

**Comment by jtwebman** [comment]
Are you going to at least update the reference to ^1.0.0 instead of ~1.0.0 which will not have the latest superagent?

**Comment by Trisha1212** [comment]
i am still facing same issue

**Comment by whistlerbrk** [comment]
I'm still running into this and I can't seem to just pass a string....
