### ISSUE TITLE
req path shouldn't be encoded 

### ISSUE THREAD

**Issue by houfeng0923** [visionmedia/supertest#220]
```
request(app)
.get('/css/??a.css,b.css')

```
when request '/css/??a.css,b.css', the path is parsed '/css/?%3Fa.css%2Cz.css=' .

now , i have to pass encoded url like this: 

```
request(app).get('/css/%3F%3Fa.css,b.css') 
```

**Comment by mikelax** [comment]
This is how URL encoding has to work, having two question marks like your example will result in a server treating the first one as the start of the query string, with the second one as the first character of the query string. 

You will need to URL encode the question marks if you want them to actually appear in the URL.
