### ISSUE TITLE
Negative tests now a PITA in 1.0 :(

### ISSUE THREAD

**Issue by dougwilson** [visionmedia/supertest#221]
Hi! Great work getting a 1.0 out! My only concern is that now it's a super PITA to do any negative tests, because even if you specifically expect a bad status code (like 400), just passing `done` from `mocha` will still cause the test to fail, since there is now a propagated error. I don't want to suppress the error like in the readme, because how do I know the error isn't a failed status code assertion?

**Comment by dougwilson** [comment]
In other words, the readme has the following, which is SUPER WRONG, because it will still make the test pass, even if the status code is not a 302, since all the test does is say "well, I got _some error_". It would be _super useful_ if a status code expect in `supertest` just suppressed the status code errors from superagent.
```js
describe('GET /redirect-url', function(){
  it('respond with 302 redirect', function(done){
    request(app)
      .get('/redirect-url')
      .expect(302, function (error) {
        (error !== null).should.be.true;
        done();
      });
  })
})
```

**Comment by jonathanong** [comment]
This is due to superagent v1. I'm pretty sure you'll have to make a change there first.

**Comment by dougwilson** [comment]
I issued a simple PR that would let `superagent` keep this behavior (which I'm not against) while keeping it easy to use `supertest` still.

**Comment by benesch** [comment]
I think the point is it makes sense that SuperAgent throws an error when a request returns a non-200 status code, since there are few cases where you use a general-purpose HTTP client to intentionally fetch an erroring resource.

But it's exceedingly common to use SuperTest to fetch an erroring resource and asset that it errors, especially when constructs like `.expect(404)` are a fundamental part of the API.

Couldn't SuperTest just null out status code errors, with no change to SuperAgent?

**Comment by dougwilson** [comment]
Indeed! I have a PR that should accomplish this :) I agree that superagent is fine, rather it is an issue with supertest.

**Comment by benesch** [comment]
Oh I missed your latest comment. I'm in total support!

**Comment by evanshortiss** [comment]
In support of this too. Started a new project this evening and spent a while wondering why this was happening until I saw the new updated README.

**Comment by mastertinner** [comment]
+1 for @dougwilson 's PR
