### ISSUE TITLE
res.clearCookie() don't work in supertest

### ISSUE THREAD

**Issue by jeremieca** [visionmedia/supertest#227]
Hello,

It seems there is a problem to remove a cookie. On logout I removed 'remember_me' cookie. And I run the following functional test : 

I simplify the test. The second request failed because I have a status 200 because remember_me cookie always exist and server reconnect.

```
   browserSession[0]
    .post('/auth/logout')
    .expect('set-cookie', /remember_me=; Path=\//)
    .end(function(err, res){
        browserSession[0]
            .get('/auth/status')
            .expect(401, done);
    });
```

Thanks !

**Comment by terencechow** [comment]
Did you ever find out the reason for this problem? Was there a solution?
