### ISSUE TITLE
Add regex status code checking

### ISSUE THREAD

**Issue by gabeio** [visionmedia/supertest#228]
I sometimes need to not care as much about the exact status code returned and care more that it is not returning a certain status code specifically. This could easily be achieved using regex as I already use it with supertest ~0.21 but 1.0 broken nearly every test I had (lots of redirecting) but there are a bunch more tests that I just can not fix with out something like `.expectnot` or to be able to do something like `.expect(/2!/)` where it just checks that the first number in the status code isn't a 2... all other should be validated with the location or just plain error.

**Comment by mikelax** [comment]
Hello, it sounds like there are two questions you are asking about. 
The first is asking if an enhancement could be implemented in supertest to allow regex expressions for HTTP response codes. 
The second question is asking about the handling of non 2xx response codes in supertest 1.0.0. This was corrected in version 1.0.1 with #224 

if the above is correct, I think having a regex response code check could be a worthwhile feature.

**Comment by gabeio** [comment]
Yeah, sorry, regex expressions for response codes is what I am asking for. Okay I think I just didn't update to 1.0.1 yet then.

**Comment by gabeio** [comment]
bump? @mikelax

**Comment by mikelax** [comment]
I would love to get this included, if you are able to submit a PR please go ahead and I will review. 
I am going to bump the milestone to 1.3 given this may change the API for the status check.
