### ISSUE TITLE
Absolute URL in request

### ISSUE THREAD

**Issue by pedroprieto** [visionmedia/supertest#231]
I can't make a request with an absolute URL. My API returns absolute URL links and I can't navigate through them. Superagent does allow it. Is it possible to fix it?

Thanks.

**Comment by mikelax** [comment]
Can you please send a code snippet of the failure and the resulting error?

**Comment by pedroprieto** [comment]
request(app)  // Or request('http://localhost:3000')
     .post('http://localhost:3000/path')
     .end(function (err, res) {
        console.log(JSON.stringify(err));
        var loc = res.header['location'];
     });

It produces the following error:

    {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

While the following works:

    request(app)  // Or request('http://localhost:3000')
     .post('/path')
     .end(function (err, res) {
        console.log(JSON.stringify(err));
        var loc = res.header['location'];
      });

I've also tried with 

    request('http://localhost:3000')

and no luck either.

**Comment by mikelax** [comment]
I see, If you want to send in an absolute URL to the post() method, then you shouldn't be passing in anything to the app function. 
See [superagent documentation](https://visionmedia.github.io/superagent/) for an example.  

In your case above, try the following:
```javascript
request
 .post('http://localhost:3000/path')
 .end(function (err, res) {
    console.log(JSON.stringify(err));
    var loc = res.header['location'];
 });
```

**Comment by pedroprieto** [comment]
I have already tried it. No luck. Error:

     TypeError: Object function (maybePromise) {
        if (typeof maybePromise.resolve === 'function' && typeof maybePromise.reject === 'function') {
          return makeModule(maybePromise);
        }  
        return defaultModule.apply(null, arguments);
     } has no method 'post'

**Comment by mikelax** [comment]
Here is a sample showing two working examples of using absolute URLs with a test. I think there might be a better way for the second test case but I couldn't figure it out as of yet. 

```javascript
var request = require('supertest')
  , express = require('express');

var app = express();

describe('GET absolute url sample', function(){
    it('should respond with a json 200 response with URL in request', function(done) {
        request('http://ip.jsontest.com')
            .get('/')
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200)
            .end(done);
    });

    it('should respond with a json 200 response with URL in get', function(done) {
        request('')
            .get('http://ip.jsontest.com/')
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200)
            .end(done);
    });
});
```

**Comment by pedroprieto** [comment]
It works! Thank you very much. I hadn't thought of that. I usually try things like the one you posted, but this time I wasn't able to find it.
Thank you for your time!
