### ISSUE TITLE
Priority of expect

### ISSUE THREAD

**Issue by Rastopyr** [visionmedia/supertest#233]
Why the body of the request is first checked, and only then the status?

In this case, if `response.body` and `response.statusCode` not to asserted expected values, `supertest` return error about `response.body`, but not about `response.statusCode`
```javascript
supertest(app).get('/someUrl')
  .expect(200) // expect `response.statusCode`
  .expect(expectedObject) // expect `response.body`
```

It not a problem. I just wonder why such an order?

**Comment by mikelax** [comment]
Dup of #173. Priority of expect calls will be status code, then headers, then body for order of operations.
