### ISSUE TITLE
expect(function(res) {}) is implemented inconsistent to documentation

### ISSUE THREAD

**Issue by saintedlama** [visionmedia/supertest#236]
The `expect(function(res) {})` documentation states:

> Pass a custom assertion function. It'll be given the response object to check. If the response is ok, it should return falsy, most commonly by not returning anything. If the check fails, throw an error or return a truthy value like a string that'll be turned into an error.

But in file `lib\test.js` at line 223 (https://github.com/visionmedia/supertest/blob/master/lib/test.js#L223) the following condition is implemented

`if (!(err instanceof Error)) continue;`

which effectively treats any non truthy value that is not an `Error` as a falsy value.

**Comment by shakiba** [comment]
The issue is made in this commit: #144.

**Comment by MartijnR** [comment]
Yes, indeed. Made me think my tests passed, when they actually failed.

**Comment by royts** [comment]
https://github.com/visionmedia/supertest/issues/327

**Comment by mikelax** [comment]
The documentation for this has been updated with PR #262
