### ISSUE TITLE
Can't pass arguments to custom expect function

### ISSUE THREAD

**Issue by jsajnani79** [visionmedia/supertest#238]
An expect callback will only receive the response as an argument. How is it possible to pass in custom arguments?

.expect(customFn(res, param1, param2))

**Comment by Rob--W** [comment]
Just use `Function.prototype.bind` - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind or pass a function to `.expect`:

```javascript
.expect(customFn.bind(param1, param2)) // is equivalent to
.expect(function(res) {
    customFn.call(this, param1, param2, res);
})
```
