### ISSUE TITLE
Request and Agent do not expose a destructor to clean up services, preventing nodejs from emitting an 'exited' event

### ISSUE THREAD

**Issue by Jhorlin** [visionmedia/supertest#243]
I am running into a common gulp-mocha issue where gulp cli completes executing all the tasks but it does not exit. This is because request creates a server when using a middleware app, but does not expose a method to destroy the procces and close the service. Since gulp cli listens for process exit event and request has created a service that is still listening the process exit event is not emitted.

**Comment by tcurdt** [comment]
I've run into a similar problem.

https://github.com/substack/tape/issues/216

Given that we cannot use the usual signal handling way there is a need for some kind of callback/hook to shut everything down properly.

**Comment by TRhode** [comment]
I'm using supertest with vows (vowsjs.org) and I believe that I need to manually clean up the server and kill the process. +1 on adding the ability to close it out cleanly rather than process.exit()

**Comment by jknight12882** [comment]
👍  on this
