### ISSUE TITLE
How to test PUT method with a body in the request?

### ISSUE THREAD

**Issue by bitliner** [visionmedia/supertest#246]
How to test PUT method specifying a body?

**Comment by bitliner** [comment]
Solved, using `.send()` method

**Comment by alexandrupetrescu94** [comment]
Can you post an example of the solution for the PUT method? Thank you!

**Comment by bitliner** [comment]
Try with following using put method instead of post

```
request(app)
            .post('/login')
            .send({
                username: 'username@wonderflow.co',
                password: 'password'
            })
            .expect(200)
            .end(function(err, res) {

                expect(res.body.token).to.be.not.undefined;
                expect(res.body.user).to.be.not.undefined;
                expect(res.body.user.username).to.be.eql('username@wonderflow.co');

                done();
            })
```

**Comment by alexandrupetrescu94** [comment]
Thank you for your response!
I had a problem with put and also trying a file upload, so there was a little problem :)

**Comment by mikelax** [comment]
Hi, for general questions like this, let's try to use StackOverflow with questions tagged supertest

http://stackoverflow.com/questions/tagged/supertest

**Comment by liesislukas** [comment]
this https://github.com/visionmedia/supertest/issues/246#issuecomment-121542653 works rgeat with POST too :) thanks
