### ISSUE TITLE
How do I get response time for each request?

### ISSUE THREAD

**Issue by naren-bhattarai** [visionmedia/supertest#261]
Apologies if it's not a right place to ask this question.

```
supertest
  .get('/something')
  .expect(200, function (res) {
      //console out time taken by '/something'
  })
  .end(done);
```

**Comment by damtsnkff** [comment]
@npm-install do you make any request before ? Especially one taking longer than 1000ms (highlighted in red) ?

Because I noticed that when a request take a long amount of time,  every request following don't show the response-time.

**Comment by drptbl** [comment]
@rimiti what is the solution?

**Comment by muthukumarsivajothi** [comment]
@rimiti @drptbl  @naren-bhattarai  did u find any solutions? I am still facing the same issue. i could not able to get response time for each requests.

**Comment by petef19** [comment]
is there an update for this question ? How can we grab the response time for a request ?

It is printed in the Test overview but does not seem to be part of the returned response object... (?)

Thanks.

**Comment by sonu-paystack** [comment]
is this implemented?
