### ISSUE TITLE
Latest version updated ??

### ISSUE THREAD

**Issue by liviez** [visionmedia/supertest#267]
Hi,

I had installed supertest 1.0.1 (released May 2015). However, I see in the repo that the dependencies have been updated, which is what I am interested in (express 4). I wonder if a version update has been forgotten or they are just release candidate changes?

**Comment by mikelax** [comment]
Hello, I was working a little while back on the next release of supertest but got a little sidetracked. I am planning to get jump back in the next couple of days and get the next release out. It will bump the version to a 1.1.0 based on a few PRs that are ready to be merged in.
