### ISSUE TITLE
expect not working properly

### ISSUE THREAD

**Issue by calidion** [visionmedia/supertest#269]
```js
'    request(server)
      .post('/auth/ack')
      .send(data)
      .expect(300)
      //.expect(data.echostr)
      .expect('acb')
      .end(function(err, res){
        console.log(err);
        if (err) throw err;
      });
```
will get error message

```js
{ [Error: expected 'acb' response body, got 'Hello world!'] expected: 'acb', actual: {}, showDiff: true }
```

but the status of this test case is passed:

    ✓ should be able to ack server auth (1513ms)

**Comment by tcurdt** [comment]
Run into the same thing. Basically it seems that as soon as there is an `end` call all the previous `expect` calls don't matter.

**Comment by tcurdt** [comment]
Not sure what you are using. If you are using `mocha` you should call the `done` callback - not throw an exception.

        .end(function(err, res) {
          if (err) return done(err);
          done();
        });

**Comment by calidion** [comment]
don't know if it if because of missing done.
