### ISSUE TITLE
multiple headers

### ISSUE THREAD

**Issue by ORESoftware** [visionmedia/supertest#270]
I have a problem with set being used for headers, 

why can't this

```javascript
    request(app)
      .get('/user')
      .set('Accept', 'application/json')
      .expect(200)
      .end(function(err, res){
      
  })
})
```

be this instead:

```javascript
   request(server)
                .post('/event')
                .headers({
                    'Accept', 'application/json'
                })
                .send(ivrNoEnrich)
                .expect(201)
                .end(function (err, res) {
                
                });
```

forgive me for being daft but isn't this more better?

**Comment by nw** [comment]
If you look at the source set actually works this way. You can pass it an object of key/val for headers and they will all be set correctly.

**Comment by ORESoftware** [comment]
it didn't work when I tried it that way...and the examples should be using
an object, not a double argument. totally ridic IMO...not the first
complaint I have with request/supertest but whatcha gonna do

**Comment by mikelax** [comment]
@ORESoftware  this is already supported with the set method. [Here is an example](https://visionmedia.github.io/superagent/#setting-header fields) from the superagent docs.
