### ISSUE TITLE
Can't parse headers when using `.options()`

### ISSUE THREAD

**Issue by diosney** [visionmedia/supertest#272]
The following is the test definition:

``` js
api = supertest(url);

describe('when OPTIONS', function () {
    it('should return only method GET', function (done) {
      api
        .options('/')
        .expect('Allow', 'GET')
        .expect(200, done);
    });
  });
```

Its keeping triggering the following error:

```
Uncaught TypeError: Cannot read property 'header' of undefined
      at _stream_readable.js:944:16
```

I already tried a lot of things without being able to make this work.
I 'm using supertest `^1.0.1` and it worked fine with version `~0.13.0`.

**Comment by diosney** [comment]
When

```js
 api
        .options('/')
        .end(function(error,res){
          if (error) return done(error);
          done()
        });
```

It says:

```
SyntaxError: Unexpected token G
      at Object.parse (native)
      at _stream_readable.js:944:16
```

**Comment by diosney** [comment]
I already detected the issue, it was that in the API I was returning an OPTIONS response with `Content-Type: application/json` but the body was an invalid JSON (it was GET,HEAD).

There is away that the library  can improve the error message for this case? If such a message would be `Invalid JSON response or Can parse body` it would be detected easier.

Thanks

**Comment by BebeSparkelSparkel** [comment]
Same problem here
