### ISSUE TITLE
Breaking API Change in 1.1.0 — Non-2xx HTTP codes doesn't trigger error

### ISSUE THREAD

**Issue by elmigranto** [visionmedia/supertest#276]
Consider following code:

``` js
var http = require('http');
var supertest = require('supertest');

var server = http.createServer(function (req, res) {
  res.writeHead(400);
  res.end();
});

supertest(server)
  .get('/')
  .end(function (err, res) {
    console.log(err ? 'has error' : 'no error');
  });

```

I tried a bunch of HTTP methods and non-2xx HTTP codes, and for all of them it prints:
-  `no error` for version 1.1.0;
- `has error` for version 1.0.1.

This looks to me like a major API change that breaks backwards compatibility and probably requires major version bump in accordance with semver, what do you think?

**Comment by DevBlaaast** [comment]
Hey @elmigranto, check this commit out : https://github.com/visionmedia/supertest/commit/4a11955cb1aca156d1481ffca913608f5eb8b217

We now need to pass `.expect(<status code>)`. Supertest will only throw an error if the status code is not the one expected.

I guess it should be a breaking changes :)

**Comment by elmigranto** [comment]
> I guess it should be a breaking changes :)

Why not bump version to 2.0.0 then?

Anyways, thans for clearing things up and making a great tool! :)

**Comment by DevBlaaast** [comment]
I'm just a user of the module, never contributed to it :) I just did read the commits to understand what was going on when I got the problem.

I guess you could send a PR and propose a major bump !

**Comment by jjacobson93** [comment]
I'm having the same issues as well. It sucks that breaking change was introduced without a major version bump. I have to fix all of my tests :/

**Comment by mikelax** [comment]
Wrangling with the major [1.0.0 change of superagent](https://github.com/visionmedia/superagent/blob/master/History.md#100--2015-03-08) caused some decisions on how to handle these non 2XX response codes. 

Please see #224 for the full history of the PR down to the original issue reported. 
Sorry for the inconvenience with the version numbering.
