### ISSUE TITLE
Error on requiring module

### ISSUE THREAD

**Issue by olivierrr** [visionmedia/supertest#279]
code: `var superTest = require('supertest');`

error: `Uncaught TypeError: Cannot read property 'prototype' of undefined`

**Comment by timc13** [comment]
i'm getting this too.  why did this happen?

**Comment by noah79** [comment]
I wasted so much time on this today trying to get my first ever set of tests up and being unable to use supertest without it throwing an error.  The offending line is in supertest/lib/agent.js line 6:

```
var Agent = require('superagent').agent
```

A change in a peer dependency, perhaps?

**Comment by mikelax** [comment]
Can you post your package.json or provide a simple use case showing this problem? 
There must be some weird edge case as this isn't happening for majority of users.

**Comment by relhtml** [comment]
> var Agent = require('superagent').agent

I'm getting the same error when requiring the module within a Jest test. However, removing the .agent part doesn't solve the problem. I'm using Supertest v3 with Jest v19.0.2.

**Comment by relhtml** [comment]
TypeError: Cannot read property 'prototype' of undefined

      at Object.<anonymous> (node_modules\supertest\lib\test.js:43:35)
      at Object.<anonymous> (node_modules\supertest\index.js:7:12)
      at Object.<anonymous> (menuPricingUI\components\GeminiFeedback\__tests__\GeminiFeedback.test.js:5:15)
      at process._tickCallback (internal\process\next_tick.js:103:7)`

**Comment by jperasmus** [comment]
@relhtml did you ever manage to get around this issue? Also using supertest with Jest.

**Comment by bwhitty** [comment]
This same issue is also present with Jest 22. I get errors like
```
    TypeError: Cannot read property 'prototype' of undefined

    > 1 | import request from 'supertest';
      2 | import webpack from 'webpack';
      3 | import getPort from 'get-port';
      4 | import {

      at Object.<anonymous> (node_modules/supertest/lib/test.js:43:36)
      at Object.<anonymous> (node_modules/supertest/index.js:7:12)
```

Which puts the failure at https://github.com/visionmedia/supertest/blob/master/lib/test.js#L43 with `Request` being what is undefined
```
Test.prototype.__proto__ = Request.prototype;
```

**Comment by mikelax** [comment]
@bwhitty  are you still having this problem with the latest version of supertest? There has since been a refactor that removes using the special `__proto__` property.

**Comment by cemusta** [comment]
I'm getting this error on jest 24.8.0 and supertest 4.0.2
