### ISSUE TITLE
[question]how to check not exist header field with supertest?

### ISSUE THREAD

**Issue by HaveF** [visionmedia/supertest#284]
If I set the express.js like this:

```
app.set("x-powered-by", false);
```

How to test this?

```
.expect('X-Powered-By', '', done)
```

will throw error: `Error: expected "X-Powered-By" header field`

```
.expect('X-Powered-By', null, done)
```

also not works.

Thanks for your help!

**Comment by AhmedAKZM** [comment]
The headers are available as an object in the response object of the ```end``` callback - you can make assertions there. The manner in which you do this depends on the testing suite. Here's an example for mocha with chai:

```javascript
var expect = require('chai').expect;
var request = require('supertest')('http://localhost:8000');

it('should not have the x-powered-by header', function(done) {
  request
    .get('')
    .end(function(err, res) {
      if (err) {
        return done(err); // done.fail(err) if using jasmine
      }

      // Ensure header does not exist
      expect(res.headers).to.not.have.key('x-powered-by');

      // All is good
      done();
    });
});
```

However, it would be nice if the ```expect``` method supported this. I'll extend the ```expect``` method to support testing the non-existence of a header, and make a pull request. The syntax I am proposing is ```expect('header-name', false, ...)```.

**Comment by ericnewton76** [comment]
+1

I need to test my app for X-Frame-Options being emitted and a special url that prevents it in certain 3rd party cases that want to use my app in an iframe. and the allow-from (uri) isnt supported universally.

So my tests need to look for X-Frame-Options being emitted in one case, and NOT being emitted with a special url.

expect("x-frame-options",false) should handle this situation.

@AhmedAKZM thanks for the workaround tip, ive been pulling my hair out trying to test this properly
