### ISSUE TITLE
Attach an array of files

### ISSUE THREAD

**Issue by thetutlage** [visionmedia/supertest#290]
`attach` method does not accept arrays, so what can be the best way to upload multiple files.

I tried this so far

```javascript
.attach('logo[0]', <filepath>)
.attach('logo[1]', <filepath>)
```

but it ends up in multiple files with different keys

**Comment by malte-wessel** [comment]
this should work:
```javascript
.attach('logo', <filepath>)
.attach('logo', <filepath>)
```
