### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by lebezee** [visionmedia/supertest#293]
Hi Guys,
I getting an error as in the heading. My test is quite simple I don't do much but set two headers. I should mention though that I only get the error when setting more than one header in my request, when setting a single header I get no errors.
The test does pass as expected the problem is that the test feedback is polluted with endless lines of stack trace.

**Comment by mikelax** [comment]
Setting multiple headers on a request is supported and should work fine. Here is a quick code snippet for how to do it. 
```javascript
            supertest(app)
                .get('/test')
                .set('Accept', 'application/json')
                .set('Content-Type', 'application/json')
                .expect(200)
                .end(function(err, res) {
                    done();
                });
```

If you have further questions, please try to post a question on stackoverflow.com using the [tag supertest](http://stackoverflow.com/questions/tagged/supertest).
