### ISSUE TITLE
npm supertest intercepts middleware and does not run boot scripts

### ISSUE THREAD

**Issue by varunj90** [visionmedia/supertest#298]
We are registering our middleware handler in server/middleware.json like the following:

![image](https://cloud.githubusercontent.com/assets/3495961/11250388/4ed468dc-8dfa-11e5-9d5a-ee502a84ad75.png)

When performing integration tests using supertest :

![image](https://cloud.githubusercontent.com/assets/3495961/11250550/e573288c-8dfa-11e5-9812-a68a3a6d8474.png)

the code does not go through our middleware which contains the error handler because of which we get errors like

here11111111111111111111111111111111111111111111:
{ [Error: Parse Error] bytesParsed: 9, code: 'HPE_INVALID_STATUS', response: undefined }

OR
here11111111111111111111111111111111111111111111:
[TypeError: Cannot read property 'header' of undefined]

We suspect that we have a missing configuration with supertest ; 
or 
We might need some code that starts up in server.js that links supertest properly using loopback.

Can you advice us on getting this to work as it is a major roadblock.

Thank you !

**Comment by varunj90** [comment]
![image](https://cloud.githubusercontent.com/assets/3495961/11304444/14bcbe56-8f76-11e5-91fe-c62e121ff610.png)

![image](https://cloud.githubusercontent.com/assets/3495961/11304458/2075e722-8f76-11e5-8d1f-1203c2d01aa9.png)

![image](https://cloud.githubusercontent.com/assets/3495961/11304475/34bdf580-8f76-11e5-90f3-de7cc988ba34.png)

Anything that is other than code 2xx ; example in this case 500; fails with 'res'  being undefined?

**Comment by varunj90** [comment]
@raymondfeng 

Latest Finding:  if we add the following code snippet for the unit tests, they actually pass
 
![image](https://cloud.githubusercontent.com/assets/3495961/11348355/1ef2799e-91f4-11e5-9ea7-d8f0d8d572e5.png)

Reference in server.js : start function

![image](https://cloud.githubusercontent.com/assets/3495961/11348379/45f561be-91f4-11e5-8a50-6379cd04022e.png)

Reference in server.js : stopServer function

![image](https://cloud.githubusercontent.com/assets/3495961/11348385/4d186f90-91f4-11e5-89c9-0ae19dc95d64.png)


Although, we shouldn't be required to start and stop a server since that's the job of supertest; but this to some extent confirms the issue of 'res' being undefined because the supertest server shuts down early?  Is this a bug in supertest? Thoughts?

**Comment by mikelax** [comment]
> Although, we shouldn't be required to start and stop a server since that's the job of supertest; but this to some extent confirms the issue of 'res' being undefined because the supertest server shuts down early? Is this a bug in supertest? Thoughts?

@varunj90 I actually don't think that supertest is responsible for setting up and tearing down an api server. The few [examples in the README.md](https://github.com/visionmedia/supertest/blob/master/Readme.md#example) include express and set up a quick express server for the sake of a quick demo. supertest is a wrapper around [superagent](https://github.com/visionmedia/superagent) and handles making requests and evaluating responses, but not the actual server.
