### ISSUE TITLE
If url omits starting /, cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by ganna-shmatova** [visionmedia/supertest#303]
Was stuck on this.
found out cause was missing beginning slash
thought that was a little odd

Stacktrace:
![image](https://cloud.githubusercontent.com/assets/7226694/11876905/fea3f0ea-a4b9-11e5-9e1d-0e4351e2af0a.png)

original url was: `email/send`.
Everything worked splendidly when url was changed to: `/email/send`

**Comment by mikelax** [comment]
This is a [requirement](https://visionmedia.github.io/superagent/#request-basics) of superagent.
You must use an absolute URL or start requests with a slash.
