### ISSUE TITLE
PUT image without multipart with query token 

### ISSUE THREAD

**Issue by justusmaier** [visionmedia/supertest#305]
I'm replicating the behavior of a signed put request with Cordova (for example to amazon s3, in this case a local PUT request).
The upload request is not multipart and only sends the image (I save it with createWriteStream(..).pipe(this.req).

I got this to work with manual tests, now I want to see this automated. 

Problems: 
- The implementation of .write() in Superagent v.1.3.0 loses the query params (including an important token)
- Supertest .pipe() implementation has an inheritance flaw/bug

When will supertest update superagent to v.1.6?
How to use .pipe() correctly?

**Comment by mikelax** [comment]
we are now updated to the latest version of superagent.
