### ISSUE TITLE
jasmine node 

### ISSUE THREAD

**Issue by arashbi** [visionmedia/supertest#306]
It seems when I am running supertest under jasmine node, it reports every as passed, when in reality it is not.
Example : 

```
    it('should pair a user and a table', function(done){
      storage.testdb();
      storage.save({"number" : 1, "name" : "Table 1"})
      .then(function(){
        request(app)
          .post('/pairs')
          .send({user : "mike", table : "1"})
          .expect(function(res){
            console.log(res);
            res.body.result = 'NOK';
        }) 
          .expect(200,done);
      });
  });
```

But it actually is a 404, I see it in the console, but expectation passes somehow

**Comment by sovattha** [comment]
+1

**Comment by ganmor** [comment]
The jasmine syntax (edge) for the done callback has changed you must use done.fail when a test has failed.
This means you cannot use expect but, you can user .end instead : 

```
.expect(200)		
.end(function (err, result) {
  if (err) {
    return done.fail(err);
 }
 done();
});
```
