### ISSUE TITLE
Test failing only on Windows

### ISSUE THREAD

**Issue by vicusbass** [visionmedia/supertest#308]
I am testing a basic REST route using mocha and supertest. For some reason the test is always failing on Windows and never failing on OSX/Linux. The failure is:

`timeout of 2000ms exceeded. Ensure the done() callback is being called in this test`

It does not make sense, I tried increasing the timeout (that's not the issue anyway, the response comes back in a few ms), treating the callback in end(), etc. Nothing works. Even weirder, if I add a second similar test AFTER this one, that test is passing. mocha version is 2.3.4, supertest is 1.1.0 

```
var expect = require('expect.js');
var request = require('supertest');
var app = require('../app');

describe('Should get Bad request for invalid domain', function () {
 it('Return 400', function (done) {
    request(app)
        .get('/api/v1/urls?domain=xxx.a')
        .expect(400, done);
 });
});
```

**Comment by saintedlama** [comment]
Could you post the app code? Using supertest on windows and never had a specific windows problem with it.

**Comment by pqrkchqps** [comment]
Same sort of issue on my windows machine when I use --watch with mocha.  It only have a window machine so I can't confirm whether it is a windows only thing, but it does work on the second try or without the --watch option.
