### ISSUE TITLE
When server is down, the error message is not useful

### ISSUE THREAD

**Issue by sakovias** [visionmedia/supertest#314]
My test suit is hitting a server with a bunch of requests and then checks on responses. `supertest` is really good for making tests on response body and status code easy!

However, when the server is down for some reason the error message doesn't allow to identify the source of the problem. Me and some other folks tripped over this a bunch of times :)

``` javascript
var request = require('supertest');
request('localhost:6237')
  .get('/')
  .expect(200)
  .end(function(err, res) {
    if (err) throw err;
    console.log('Success', res.body);
  });
```

Running this given the server at `localhost:6237` is down results in this stack trace:

```
$ node test.js
/path/to/test.js:8
    if (err) throw err;
                   ^
TypeError: Cannot read property 'status' of undefined
```

Is it something I can go ahead and fix or it's intended functionality?

**Comment by malhar-trivedi** [comment]
@sakovias https://github.com/visionmedia/supertest/issues/237

**Comment by jxm262** [comment]
After looking at #237 , I'm seeing the same error on the newest version of master.  Perhaps the fix was never merged?

**Comment by parxier** [comment]
Is there any update on this one?
Is it possible to merge #237 fix into latest version?

**Comment by contra** [comment]
I'm still getting this error, but it seems to happen randomly. Running the tests again it doesn't happen, maybe 1 out of every 30 runs this happens on a random test.

**Comment by bkeepers** [comment]
https://github.com/visionmedia/supertest/pull/446 should help reveal the underlying error here.
