### ISSUE TITLE
mocking parts of a controller

### ISSUE THREAD

**Issue by soupman99** [visionmedia/supertest#321]
I'm trying to test out my routes, but my controller methods rely on 3rd party services.  Is there a way to mock these third party services using sinon with supertest so my 3rd party api calls get mocked properly and aren't "live" calls?

**Comment by saintedlama** [comment]
Basically stub 3rd party services before running supertest and unstub after

```
describe('GET /user', function(){
  it('respond with json', function(done){
    var stubbed = sinon.stub(3rdparty, 'service'...
    request(app)
      .get('/user')
      .set('Accept', 'application/json')
      .expect('Content-Type', /json/)
      .expect(200, function(err) {
         if (err) { return done(err); }

         stubbed.restore();
      });
  })
})
```

**Comment by shunchu** [comment]
@soupman99 Did you ever get a chance to figure this out? I'm running into similar issues with sinon and nock unable to intercept outgoing live calls to 3rd party services when those calls are made as part of calls to controllers (e.g. `post`ing to controller and then in the controller, maybe an outgoing `axios.post...` call... and that `axios` call is unstoppable!!). Thanks in advance.
