### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by PlasmaPower** [visionmedia/supertest#322]
The pulse for a month shows just one change, a PR was merged to fix a breaking change. Is this project still alive? Is there a fork that is being maintained? `supertest-as-promised` looks like the way forward, but it doesn't seem to be maintained either.

Anybody have any good alternatives?

**Comment by zensh** [comment]
We need a maintainer to deal PRs @mikelax

**Comment by nfroidure** [comment]
Imo, if it works and there are no better alternative (i think it is the case right now), there is no reason to change it frequently until there are blocking bugs.

Also, having a quick look at issues makes me think there are a lot of invalid ones.

Since i use it heavily, i'm ok to make some issues/PR triage.

**Comment by PlasmaPower** [comment]
I've created [assert-request](https://www.npmjs.com/package/assert-request) as a new promise-based alternative.

**Comment by mikelax** [comment]
Hi all. I picked up this project as the previous maintainer and original owner had given up interest. 
I have been trying to keep on top of critical bugs, push out a few updates and keep parity with superagent updates. 

@nfroidure you are correct. A lot of the issues opened are really questions on usage. I have been trying to move those discussions to the [superteset tag at stackoverflow](http://stackoverflow.com/questions/tagged/supertest)

I can continue to do the same, but I would welcome help for trying to think up a larger roadmap for 2.0 release.

**Comment by mikelax** [comment]
I can start a roadmap of things that I think need to be added, upgraded, etc and people can comment and we can use that as a starting point.

**Comment by saintedlama** [comment]
@mikelax Could help you a bit with bug triage and stuff

**Comment by mikelax** [comment]
@saintedlama  if you want to help me with with some PR reviews and help get some PRs identified for 1.3 that would be really useful.

**Comment by saintedlama** [comment]
@mikelax sorry for my late response - what are your plans for 1.3? I could review PRs and add some "looks fine for 1.3" comment...

**Comment by mikelax** [comment]
New release published, see #474.

**Comment by rook2pawn** [comment]
@nfroidure @PlasmaPower @mikelax i wrote a ultra-short very readable version of supertest that i call [supertest-light](https://github.com/rook2pawn/supertest-light). I would love if you could check it out.
