### ISSUE TITLE
return string doesn't work when using function as expact paramter

### ISSUE THREAD

**Issue by chentsulin** [visionmedia/supertest#327]
return string will not throw error, and it incorrectly pass the test:
```js
.expect(function (res) {
  if (true) {
    return 'not correctly';
  }
})
```

Only throw error works:

```js
.expect(function (res) {
  if (true) {
    throw new Error('not correctly');
  }
})
```

Doesn't match the usage in Readme https://github.com/visionmedia/supertest#expectfunctionres-

**Comment by cressie176** [comment]
Also seeing this.

**Comment by chentsulin** [comment]
It seems that `_assertFunction` only handle return Error, throw Error, but not string..

```js
if (err instanceof Error) return err;
```
https://github.com/visionmedia/supertest/blob/master/lib/test.js#L269

It maybe works if we do something like this:

```js
if (typeof err === 'string') err = new Error(err);
if (err instanceof Error) return err;
```js

**Comment by royts** [comment]
see the same issue.

**Comment by mikelax** [comment]
This is a dup of PR #262 I just merged that in.
