### ISSUE TITLE
supertest-restify-gzipresponse-file-upload

### ISSUE THREAD

**Issue by edorivai** [visionmedia/supertest#328]
I've asked this question on stackoverflow without any luck yet:
http://stackoverflow.com/questions/36306505/supertest-restify-gzipresponse-file-upload

I'm getting

    TypeError: Cannot read property 'status' of undefined

when attempting to upload a file using supertest to a simple restify server, with `gzipResponse` turned on.

Versions etc:

    $ npm list | grep 'super\|mocha\|restify'
    ├─┬ mocha@2.4.5
    ├─┬ restify@4.0.4
    └─┬ supertest@1.2.0
      └─┬ superagent@1.8.3
    
    $ node -v
    v5.5.0

The server:

```js
const restify = require('restify');
const server = restify.createServer();
    
server.use(restify.gzipResponse());
    
server.put('image', (req, res) => {
    res.send(200, 'OK!');
});
    
// For testing
module.exports = server;

// For actually running the server  
if (!module.parent) {
    server.listen(8888);
    console.log('Listening on 8888');
}

```

The test:

```js
const request = require('supertest');
const server = require('./index');
const path = require('path');
    
describe('insertImage', function () {
    
    it('should send an image', done => {
        request(server)
        .put('/image')
        .attach('image', path.join(__dirname, 'pc.png'))
        .expect(200, done);
    });
    	
});
```

The test will pass when `gzipResponse` is disabled, and it will also pass if no file is attached.

Moreover, when running the server, and just firing a request with curl, the server responds successfully.

`curl -X PUT -F image=@./pc.png local8888/image`

So this makes me think the problem is not with Restify/gzipResponse, but rather with supertest/superagent. What do you guys think?

**Comment by mikelax** [comment]
@edorivai  I just left an [answer on the SO question](http://stackoverflow.com/questions/36306505/supertest-restify-gzipresponse-file-upload/36610733#36610733). TLDR I think that supertest handles gzip responses just fine. There must be some issue with the server set up for the test.

**Comment by edorivai** [comment]
I see, but what do you think about the fact that curl seems to work just fine?

**Comment by DonutEspresso** [comment]
Not really sure. Using the same test server curl and request appears to be working as well:

```js
        request.put({
            url: 'http://localhost:3000/image',
            method: 'put',
            body: fs.createReadStream('./pc.png')
        }, function(err, res, body) {
            console.warn(body);
            return done();
        });
```

Based on these results I'd suspect supertest, but if they were unable to reproduce, then it could be something specific to your environment. Not sure what to tell you besides rm -rf node_modules, and reinstalling everything to see if it helps.

**Comment by edorivai** [comment]
You know what, I even got a completely new computer. Obviously installed everything from scratch; OS, node (nvm), all of the modules etc, problem still persists. Not sure what to make of this.

**Comment by DonutEspresso** [comment]
Bummer - not sure what to tell you. I just pulled down your snippets here and ran them locally and it seemed to be working for me. What OS/node version are you using? What commands are you using to start your server and run the tests?

**Comment by JeffML** [comment]
posted comment for similar (if not the same issue) on #348

**Comment by edorivai** [comment]
Hey, on request of the people over at `restify`, I've setup a repo that produces the issue:
https://github.com/edorivai/supertest-restify-upload

According to [this comment](https://github.com/restify/node-restify/issues/1054#issuecomment-299872303), the restify peeps think the problem is with supertest:

> It doesn't look like restify is on the path of this exception, I'm fairly certain this issue is down inside of supertest. _assertStatus inside of lib/test.js expects to be given a res object and it doesn't appear one is being passed in. Hope that helps!

**Comment by retrohacker** [comment]
Hey y'all,

@retrohacker from the restify repo here. Happy to work together to try to solve this bug :smile: I hate to see @edorivai being bounced back and forth. Where we are at right now is that it doesn't appear `_assertStatus` is getting a `res` object back from supertest. It may be that restify is breaking an assumption that supertest makes, but I don't know enough about supertest to get much further at this point.

**Comment by retrohacker** [comment]
Sorry, just read this thread. @edorivai, have you run the patch from #348? Looks pretty much identical to what we are describing here.

**Comment by edorivai** [comment]
I didn't, will check tomorrow!

**Comment by edorivai** [comment]
@retrohacker The `v5` branch in my repo uses supertest v3: https://github.com/edorivai/supertest-restify-upload/blob/v5/package.json#L6 

And the issue still persists there.
