### ISSUE TITLE
ECONNRESET with .attach and server does not consume request body on windows

### ISSUE THREAD

**Issue by MugeSo** [visionmedia/supertest#332]
Following code gets error on only windows.

``` js
var app = express();
app.post('/', function(req, res) {
  res.status(200).end();
});

var file = path.join(__dirname, 'fixtures/attach-file.txt');
request(app)
  .post('/')
  .attach('file', , 'file.txt')
  .end(function(err) {
    if (err) return done(err);
    done();
  });
```

I try same thing for `superagent` in https://github.com/MugeSo/superagent/tree/fix-econnreset-on-attach-file, but it cannot reproduce.

**Comment by pablodenadai** [comment]
Hi @MugeSo. Do you have any updates on this issue?

I'm getting the same problem. Please see versions below:
- supertest@1.2.0
- superagent@1.8.5
