### ISSUE TITLE
Cant set request timeout

### ISSUE THREAD

**Issue by arnoldmq** [visionmedia/supertest#334]
I'm trying to test a file upload api with large files but it seems to timeout.
my api has set the request timeout to infinity (expressjs)
`server = https.createServer(options, app).listen(app.get('httpsport'), function () {
            console.log("Listening on port " + app.get('httpsport') + "...");
        });
        server.timeout = 0;`

and I have set the mocha test timeout to infinity too.
`var aboveLimit = testCases.above_limit_files;
describe("testing file upload", function () {
    aboveLimit.forEach(function (file) {
        it('should reject files larger then set upload limit (using:' + file.fileName + ')', function (done) {
            this.timeout(0);
            var route = '/file'
            request.agent(testUtil.server())//testUtil.server() returns the express app from above
                .post(route)
                .attach('file', path.join(testFilesPath, file.fileName))
                .expect(500)
                .end(function (err, response) {
                    if (err) {
                        return done(err);
                    }
                    done();
                });
        })
    })
});`

so the only thing left that could be timing out is supertest.
i went in to the source code for supertest and added the line 
`app.timeout = 0;` (index.js) and now it works but i dont know how to change the timeout without changing 
the source code.
`module.exports = function(app){
  if ('function' == typeof app) app = http.createServer(app);
  var obj = {};
    app.timeout = 0;//this prevents the timeout
  methods.forEach(function(method){
    obj[method] = function(url){
      return new Test(app, method, url);
    };
  });`

**Comment by WIP42** [comment]
@arnoldmq / Danny; is this workaround still working for you? 

I have supertest version # 2.0.1 / 2016-10-19 & 
superagent # 2.3.0

installed recently from NPM and running my tests, I always get a 2000ms timeout even with the suggested workaround.

Thank you in advance
Pierre

**Comment by arnoldmq** [comment]
@WIP42 I have not updated yet and probably wont update for a while, have you set the timeout in the other places too? I found there were three places that can time out when doing long request, one is the express app (your server), the other can be mocha(if you are using mocha), it times out too and lastly it could be supertest. so if you haven't set those timeouts to infinity yet, try doing it and maybe it will work.
