### ISSUE TITLE
SuperTest encode # character

### ISSUE THREAD

**Issue by roccomuso** [visionmedia/supertest#339]
Supertest (through SuperAgent) runs `encodeURIComponent` on all query keys. But what if I'd like to call something like this:

```
       request(url)
         .get('/data/#')
         .set('X-www-app', 'hello')
         .query({limit: 2})
         .expect('Content-Type', /json/)
         .expect(200)
         .end(function(err,res) {
           if (err) {
             debug(res.body);
             throw err;
           }

         });
```

Do I need to manually encode the `#` character in the `get` method?

**Comment by aimer1124** [comment]
I use this to encode(base64) my password

`new Buffer(password").toString("base64")`
