### ISSUE TITLE
Can I set (mock) the response body?

### ISSUE THREAD

**Issue by mayacr86** [visionmedia/supertest#341]
Hi!

I'm currently using "supertest" to test some express routes in my Node.js application. (I'm also using sinon and chai.)

I was wondering if the is a way to **mock the response** so that I don't have to rely on a real HTTP connection to my routes and to any other external services that they might call.

Something like this:

`
      const request = require('supertest');
      const server = require('./server');
      const expectedJson = { 'message': 'Hi!' };

```
  request(server)
      .post('/some/route')
      .expect(200)
      .**magicFunctionThatSetsTheResponseBody(expectedJson)**
      .end(function(err, res){
         expect(res.body).to.equal(expectedJson);
         if (err) {
          return done(err);
         }
         done();
      });
```

`
_The idea behind this, is to verify if nothing has changed within the functionality (controller, etc) that is called within that given route._

**Comment by mikelax** [comment]
@mayacr86  if you are using sinon then you should be able to mock the response on the server-side. 
I think that falls outside the scope of supertest. supertest would make the request to a "server", other libs are able to mock the server to provide a test response.

**Comment by mayacr86** [comment]
Thanks for the quick response @mikelax ! 

Here's the "issue"...
I have use sinon.stub to mock Node's http module on other unit test, and that works... But when I try to do the same and combine it with "supertest", I keep getting the same error over and over... Here is a snippet of the code:

`  
// Unit Testing related imports
const chai = require('chai');
const expect = chai.expect;
const sinon = require('sinon');

// Functionality related imports
const http = require('http');
const PassThrough = require('stream').PassThrough;

describe('My Service Spec', function () {

// Stub for the http module.
  let stubHttpRequest;

  beforeEach(function () {
    stubHttpRequest = sinon.stub(http, 'request');
  });

  afterEach(function () {
    http.request.restore();
  });`

**Comment by indcoder** [comment]
@mayacr86  have you tried yielding the stubbed request  [I have used the Unauthorized code below as an example]
`
     stubHttpRequest.yields({statusCode:401});
`

**Comment by ravichandranjv** [comment]
I am using the get method to a route that calls a methos that sets some JSON data in the response object.

```
var request = require('supertest');
var sinon     = require('sinon');
var spy=sinon.spy();
describe('simple test of about route with params',function(){
	var server;
	beforeEach(function () {
  		server = require('../server').server;
	});

it ('matches the response JSON when the about page is called',function(done){
	var getSpy=sinon.spy(server,'get');
	const expectedJson = {"data":{"username":"hellojv"}};

 	request(server)
    	.get('/about/jv')
    	.expect(200)
    	.end(function (err, response) {
	 sinon.assert.match(response.body, expectedJson);	
	done();
	});
});
});
```
The sinon spy is passed the 'server' that encapsulates the server.js and which contains the express route and is invoked by 'supertest'. In the server.js, a call to a method populates the response object. Please check out the full example [here](https://github.com/ravichandranjv/SinonAssertionOnResponse)
