### ISSUE TITLE
console message if test is passed.

### ISSUE THREAD

**Issue by georgi-k-small** [visionmedia/supertest#349]
I would like to display if test is passed after expect.

something like
expect(value).toBe(3);
done()

**Comment by saintedlama** [comment]
Just use the `end` function to console.log

```js
.end(function(err, res) {
    if (err) throw err;

    console.log('test passed');
    done();
  });
```

**Comment by georgi-kovachev** [comment]
Hi Saint.
This is code and I am using .then method.
Should I change to .end ?

This is the code.

it('AllWeight', function(done) {

			console.log('Test: standardContainerService.AllWeight is doing');

			let customerId = mongoose.Types.ObjectId('5387721584ae74ea3e415832');

			standardContainerService.AllWeight(customerId).then( (res) => {

				console.log('resp', res);
				expect(typeof res).toBe("number");
				expect(res).toBe(330);
				done();

			}).catch( (err) => {
				console.log("err", err)
			});
		});
