### ISSUE TITLE
Can't upload files with authenication

### ISSUE THREAD

**Issue by arieljannai** [visionmedia/supertest#351]
Hi,

I'm trying to upload a files from supertest (the server is using multer) and the upload demand authentication.
When I only use the `attach` method, it works fine; When only using `auth` it also works fine.
But when using both of them - nothing happens.

Example code that does not work:

``` js
request(app)
    .post('/upload')
    .auth(username, password)
    .attach('upload', fileToUpload)
    .expect(200)
```

Am I missing something?

Thanks!

**Comment by lovelydreamer** [comment]
I have a similar issue. I can't use .send w/ a token, and attach w/ a file.
