### ISSUE TITLE
Can I use AWS Signing/Authentication for supertest requests

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [visionmedia/supertest#354]
I want to test an API build with AWS API Gateway. For this the requests need to be signed with the method described here: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

Can this be done with Supertest?

**Comment by mikelax** [comment]
@RudolfVonKrugstein  yes supertest should work fine with AWS Signed requests. 
At the end of the day, the "signed" request being made is just calculating the correct value to send for the ```Authorization``` request header.

**Comment by Galileo1** [comment]
@mikelax I know this is closed issue but can you please give an example of PUT request using supertest. I am trying to hit lambda using apigateway and I keep on getting error 
` The request signature we calculated does not match the signature you provided.` .  I am using [aws4](https://github.com/mhart/aws4) nodejs library to generate signature but it doesn't work with lambda.Buy if I user the logic to hit the same endpoint using request library it work fine. Any help ?
