### ISSUE TITLE
Test fails with .send and .attach - aka how do I send a token and upload an image/file in a test?

### ISSUE THREAD

**Issue by lovelydreamer** [visionmedia/supertest#356]
It's killing me already. What am I doing wrong, or is this a legit bug?

My test w/out a token passes, and with fails. More precise details below.

https://stackoverflow.com/questions/38402244/how-to-unit-test-file-upload-with-supertest-and-send-a-token

**Comment by rafis** [comment]
(Cool photo, can't even believe you can be a nodejs developer.)
Seems you can not mix JSON body `.send({})` with multipart form-data body `.attach()`. Instead you can stick with multipart form-data and try this:

              .set('Accept', 'application.json')
              .field('token', config.token)
              .field('vehicle_vin', "randomVIN")
              .attach('file', '/Users/moi/Desktop/unit_test_extravaganza/hardwork.jpg')

**Comment by delprofundo** [comment]
wow so that really happened :| gross

**Comment by JamieCorkhill** [comment]
@rafis It's been three years, but what gives you the right to say something like that? @lovelydreamer Can be just as good a developer as anyone can.

**Comment by joemckie** [comment]
@rafis didn't know cats could be developers either 🙄

**Comment by VitorGouveia** [comment]
@rafis would you please apologize to him?
