### ISSUE TITLE
update changelog for v2

### ISSUE THREAD

**Issue by jonathanong** [visionmedia/supertest#360]
please :)

as far as i can tell, you just updated superagent, but it's nice to know none of `supertest`'s APIs were changed

**Comment by mikelax** [comment]
correct, the only change was to bump the version of superagent to 2.0.0. 
As [that version lists](https://github.com/visionmedia/superagent/releases/tag/v2.0.0) many breaking (and exciting new) changes, I decided to bump supertest to 2.0.0 as well since they are closely related.
