### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by nicofr83** [visionmedia/supertest#363]
Is it possible to superset an express server, using http and socket.io? What is the server name and port I have to use for connecting my testing client socket ?

**Comment by mathieug** [comment]
I've tweaked something thanks to https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/lib/test.js#L54-L63.

Here is my code to retrieve the port and protocol:
```javascript
  if (!globalContext.server.address()) {
    globalContext.server.listen(0);
  }
  const { port } = globalContext.server.address();
  const protocol = globalContext.server instanceof https.Server ? 'https' : 'http';
```

Then I'm able to connect (with socket.io-client):
```javascript
const socket = io(`${protocol}://127.0.0.1:${port}`);
```
