### ISSUE TITLE
History missing for 2.0.0

### ISSUE THREAD

**Issue by ErisDS** [visionmedia/supertest#364]
Just a heads up, the history.md file only includes info up to 1.2.0 and has no entry for 2.0.0.

Would be nice if this could be added.

**Comment by blacksonic** [comment]
It would be really helpful, because 2.0 makes ```co-supertest``` obsolete and introduces Promise based handling of requests (you can leave callbacks).

https://github.com/visionmedia/supertest/issues/141
https://github.com/avbel/co-supertest/issues/9

**Comment by mikelax** [comment]
Just updated the History doc for v2.0.0 in [this commit](https://github.com/visionmedia/supertest/commit/cf9f991b6cd8dd85986975abe9763d94f44a1bc0)
