### ISSUE TITLE
supertest throwing 404 error when stress testing express router

### ISSUE THREAD

**Issue by jon301** [visionmedia/supertest#377]
Hi,

I've made a repo so you can reproduce the issue :
https://github.com/jon301/express-router-test

What you need to do :

```
npm install -g gulp-cli
git clone https://github.com/jon301/express-router-test.git
cd express-router-test
npm install
gulp test
```

This will do many requests against the same route and will crash after a while.

**Comment by marcelino-m** [comment]
Similar isue here!

**Comment by Dr8f** [comment]
I've got the same. It's very annoying.

**Comment by bananaappletw** [comment]
@jon301 @marcelino-m @Dr8f  
Hey I try your example, and then upgrade `supertest` to 2.0.1
And it won't crash.
Would you mind try again with newer version of `supertest`?

**Comment by jon301** [comment]
Hi @bananaappletw,
I've just upgraded the dependencies in my repository and still get the same error :

![image](https://cloud.githubusercontent.com/assets/122108/20340988/7c931bb6-abe4-11e6-8878-2525b0170ec1.png)

**Comment by bananaappletw** [comment]
@jon301 
I tried again.
It happened.
Seems tests won't  pass every time.
Sorry for previous wrong comment.
This issue exists!!!
