### ISSUE TITLE
Testing a restricted by IP path (no proxy)

### ISSUE THREAD

**Issue by zurfyx** [visionmedia/supertest#388]
How are we supposed to test paths that require a certain IP?

In the case of using a proxy, we can pass it into the headers:
`request.set('X-Forwarded-For', ip)`

An alternative to this would be to whitelist `127.0.0.1` as well, or to force the tests to run under the proxy configuration, but I'm not sure whether these are the most appropriate solutions.

**Comment by swunderlich** [comment]
@zurfyx Dealing with this right now - what was your solution?

**Comment by VitorGouveia** [comment]
Did you guys find something? I really need it now to test ip bans
