### ISSUE TITLE
Expect multiple possible status code values

### ISSUE THREAD

**Issue by drauschenbach** [visionmedia/supertest#389]
When testing POST operations against a service that performs de-duping, it's common that I need to test for either `201` or `302` status codes.

It seems like it'd be easy to support in the code.

Here's what I'd like to do:

```javascript
.expect([201,302])
```

**Comment by sugarme** [comment]
alternatively, it might be implemented with `expect(function(res){...}`?

**Comment by jderijke** [comment]
this one received 14 thumbs up. i can't see the dates on these, but the too-old label should be based on the last thumbs-up rather than the date this was requested

**Comment by juanvillegas** [comment]
So necessary!

**Comment by juanvillegas** [comment]
Can someone confirm if this is desired/not already done? If so, I may be able to add the assertion in my free time.

**Comment by joniba** [comment]
any workaround?

**Comment by juanvillegas** [comment]
@joniba @jderijke @rimiti Sent a PR here: https://github.com/visionmedia/supertest/pull/715

**Comment by sharq88** [comment]
As sugarme suggested, it was pretty simple to implement. FYI: 
```
.expect ( r => [ 422, 404 ].includes ( r.status ) )
```
