### ISSUE TITLE
How can I close mongoose connections and my server (node+express) at the end of the test?

### ISSUE THREAD

**Issue by Ks89** [visionmedia/supertest#390]
I'm having an issue with gulp-mocha, because it seems that there are connections still open or something else that prevent gulp to stop.

My unit tests are working adding "mongoose.disconnect()" at the end, but not my integration tests with supertest. I tried to add mongoose.disconnect() at the end without success. Probably this is not enough, since mongoose is started by my app.js and not manually inside my test (as with unit tests).
So i want to try to force to stop everything at the end of my test, for instance my server (app.js, created with express.js).

How can I do this?

I know that it seems crazy, but also this issue is crazy.
Probably its not an issue of supertest, gulp-mocha and so on...I only need suggestions to fix this problem.

Also, these two issues seem similar https://github.com/SBoudrias/gulp-istanbul/issues/92 and https://github.com/sindresorhus/gulp-mocha/issues/118

I'm using supertest in this way:
```
var agent = require('supertest').agent(app);
```

**Comment by ravichandranjv** [comment]
It cannot possibly be a mongoose problem but a callback not returning or a promise not resolved. 

If you are using gulp, this answer will be useful as it works for me. gulp starts supertest as I use it but I guess you can use the same for yours to set a timeout value and see if it exits.

`gulp.task(' ', function () {
	gulp.src(' .js')
		.pipe(gulpmocha(),setTimeout(function() {
		cb();
  	}, 5000))
});
function cb(){
process.exit(1);
}`

**Comment by Ks89** [comment]
Thank u. Yes I fixed this issue a couple of months ago removing gulp. However thank u XD.
