### ISSUE TITLE
Path prefix

### ISSUE THREAD

**Issue by rodrigowirth** [visionmedia/supertest#393]
It would be good to have a way to define a default prefix for the paths. For example:

```
const options = {
  pathPrefix: '/api',
};

supertest(app, options);
```

An so all the requests will receive the `/api` prefix.

**Comment by fate-lovely** [comment]
Hi, Any updates now?

**Comment by fate-lovely** [comment]
Hi @rodrigowirth 
Thank you, it's convenient and helpful.
