### ISSUE TITLE
Add section for testing HTTPS server on README for skipping SSL Certificate Verification

### ISSUE THREAD

**Issue by tejashah88** [visionmedia/supertest#396]
I've just recently been trying to test node https servers and I've noticed that you supposedly have to add this line: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` (source: #146). It would be nice if someone can add this note somewhere in the [README](https://github.com/visionmedia/supertest/blob/master/README.md).

**Comment by RobertDiebels** [comment]
Would like this too.

**Comment by rimiti** [comment]
Anyone to create the PR ? 😃

**Comment by tejashah88** [comment]
@rimiti I can get working on that!
