### ISSUE TITLE
error 400 returns resolved promise

### ISSUE THREAD

**Issue by brenthmiras** [visionmedia/supertest#397]
I have this code:
`    api.post('/auth/login')

    .send({
        email: user.email,
        password: user.password
    })
    .end( (err, res) => {
        console.log(res.status);
        console.log(err)
    });
`
I get a status of 400 but I get err as undefined. Is this expected behavior? 400 is an error response why is err undefined?

**Comment by spencerbeggs** [comment]
400 is a valid response from a server. The err argument is only defined when an error happened in the actual execution of the send method.

**Comment by mikelax** [comment]
I want to think about this one a bit. 
superagent treats [4xx and 5xx response codes](https://visionmedia.github.io/superagent/#error-handling) as actual errors. I need to see if this is new functionality, but we may want to consider parity in supertest.

**Comment by DDDgfx** [comment]
Basically, the question is: Is the success/fail model like jQuery or like fetch? I would argue that as fetch will be the emerging standard you only handle 500s as actual errors. But that is just my preference.

**Comment by spencerbeggs** [comment]
Basically, the question is: Is the success/fail model like jQuery or like fetch? I would argue that as fetch will be the emerging standard you only handle 500s as actual errors. But that is just my preference.

**Comment by kwiniarski** [comment]
supertest is based on SuperAgent, where this behavior can be controlled. From [SuperAgent documentation on error handling](http://visionmedia.github.io/superagent/#error-handling):

> Note that a 4xx or 5xx response with super agent are considered an error by default.

> Alternatively, you can use the `.ok(callback)` method to decide whether a response is an error or not.

It seems that supertest is missing this kind of functionality.
