### ISSUE TITLE
Set Authorization header to post request

### ISSUE THREAD

**Issue by khotey** [visionmedia/supertest#398]
1. Request:
```
request(app)
      .post('/api/categories')
      .send(category)
      .set({ Authorization: token })
      .end((err, res) => {
        const newCategory = res.body;

        expect(res.status).to.be.equal(200);
        expect(newCategory).to.be.equal(category);

        done();
      });
```

Error:
`Error: "value" required in setHeader("Authorization", value)`

2. Request:
```
request(app)
      .post('/api/categories')
      .send(category)
      .setHeader('Authorization', token)
      .end((err, res) => {
        const newCategory = res.body;

        expect(res.status).to.be.equal(200);
        expect(newCategory).to.be.equal(category);

        done();
      });
```

Error:
`TypeError: (0 , _supertest2.default)(...).post(...).send(...).setHeader is not a function`

How set header to post request ?

**Comment by mikelax** [comment]
You do want to use the `.set` function. 
You should be able to pass a single JSON object or two parameters for the key and value. 

```
.set('Accept', 'application/json')
```

```
.set({ 'API-Key': 'foobar', Accept: 'application/json' })
```

In your first example I would say that there is a problem with the variable `token`.

**Comment by IvanCaro** [comment]
this does not work.

**Comment by gilbert** [comment]
Note that you have to call `.set()` AFTER calling `.post()`, not before. For example:

```js
request(app)
  .set('Authorization', 'abc123') // DOES NOT WORK
  .post('/api')

request(app)
  .post('/api')
  .set('Authorization', 'abc123') // Works.
```

**Comment by JafarAkhondali** [comment]
> Note that you have to call `.set()` AFTER calling `.post()`, not before. For example:
> 
> ```js
> request(app)
>   .set('Authorization', 'abc123') // DOES NOT WORK
>   .post('/api')
> 
> request(app)
>   .post('/api')
>   .set('Authorization', 'abc123') // Works.
> ```

It's TERRIBLE !!!
Suppose i have multiple routes to test, which all are protected by same authentication middleware ( using headers). This way, I have to set header independently for all of them!!

**Comment by christopheelkhoury** [comment]
> > Note that you have to call `.set()` AFTER calling `.post()`, not before. For example:
> > ```js
> > request(app)
> >   .set('Authorization', 'abc123') // DOES NOT WORK
> >   .post('/api')
> > 
> > request(app)
> >   .post('/api')
> >   .set('Authorization', 'abc123') // Works.
> > ```
> 
> It's TERRIBLE !!!
> Suppose i have multiple routes to test, which all are protected by same authentication middleware ( using headers). This way, I have to set header independently for all of them!!

Well it would only make sense to do that since in a real-life scenario you are making separate HTTP Requests, each having its own separate Header. Unless I understood you wrong?

**Comment by JafarAkhondali** [comment]
@christopheelkhoury In a real-life app, i would set auth header in state and create a new instance of HttpRequest which hold the auth header. For example this is my HttpService:
```

export default () => {
  return axios.create({
    baseURL: `${config.BASE_URL}/${config.API_VERSION}`,
    headers: {
      'blog-admin': store.state.Auth.token || '',
      'Cache-Control': 'no-cache'
    }
  })
}
```
And i'll call it like:
```
export function index() {
  return Http().get('/posts')
}
``
So there is no duplication of code and i can change header or auth method easily by changing one line of code. But the syntax in super test makes me to set header separately for each request which is not clean and not DRY

**Comment by Rupeshiya** [comment]
@JafarAkhondali If you are talking about setting up the header for multiple routes then you can do something like make function which will execute before all the test case and freom there get that header value and set it in others routes so in that way you dont have to write the same request code all the time whereas only thing you have to do is to set the value using ```.set('Authorization', value)```

Hope this helps.

**Comment by vegaByte** [comment]
Separe the `request` logic from all your tests simulating supertest(url).method()

`
const URL = `My Endpoint`;
const TOKEN = 'Secret';

const hook = (method = 'post') => (args) =>
  supertest(URL)
    [method](args)
    .set('Authorization', `Basic ${TOKEN}`);

const request = {
  post: hook('post'),
  get: hook('get'),
  put: hook('put'),
  delete: hook('delete'),
};

export default request;
`

I dont touch my tests code

**Comment by alessioerosferri** [comment]
I have worked around this just by making sure that supertest specifies the Accept header. oas-tools seems to be defaulting to application/json if no Accept header is defined.
`describe("And the body is empty", () => {
    test("a 400 HTTP status code is sent back", async () => {
      const res = await request(app)
        .post('/v1/screenshots')
        .set({'Accept': 'text/plain'})
        .send({
          date: "",
          time: "",
          image: "",
          campaign: "",
          format: "",
          panel_id: "",
          unit_id: ""
        })
    });
  });`
Above works if content type in response is set to "text/plain".

I was very curious at why this was working when the app was running but not during the unit tests. Postman and pretty much all the browsers by default add the accept header to be "*/*". Supertest doesn't and this is why it happened.
I hope this helps as it did with me ;)

**Comment by AndonMitev** [comment]
I'm trying to set header but is not part of the headers

```
 await request(app)
            .get('/user/all')
            .set({
                Authorization: 'abc123',
            })
            .expect(({ headers }) => {
                console.log(headers);
            })
            .expect(HttpStatus.BAD_REQUEST);
```

This is the headers object:

```
 {
      'content-security-policy': "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
      'x-dns-prefetch-control': 'off',
      'expect-ct': 'max-age=0',
      'x-frame-options': 'SAMEORIGIN',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'x-permitted-cross-domain-policies': 'none',
      'referrer-policy': 'no-referrer',
      'x-xss-protection': '0',
      'access-control-allow-origin': '*',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '43',
      etag: 'W/"2b-hGShxOkieaAVDloBubJVM+h58D8"',
      date: 'Thu, 17 Dec 2020 11:07:30 GMT',
      connection: 'close'
    }
```

Any idea how to append Authorization to the headers?

**Comment by thelebdev** [comment]
> I'm trying to set header but is not part of the headers
> 
> ```
>  await request(app)
>             .get('/user/all')
>             .set({
>                 Authorization: 'abc123',
>             })
>             .expect(({ headers }) => {
>                 console.log(headers);
>             })
>             .expect(HttpStatus.BAD_REQUEST);
> ```
> 
> This is the headers object:
> 
> ```
>  {
>       'content-security-policy': "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
>       'x-dns-prefetch-control': 'off',
>       'expect-ct': 'max-age=0',
>       'x-frame-options': 'SAMEORIGIN',
>       'strict-transport-security': 'max-age=15552000; includeSubDomains',
>       'x-download-options': 'noopen',
>       'x-content-type-options': 'nosniff',
>       'x-permitted-cross-domain-policies': 'none',
>       'referrer-policy': 'no-referrer',
>       'x-xss-protection': '0',
>       'access-control-allow-origin': '*',
>       'content-type': 'application/json; charset=utf-8',
>       'content-length': '43',
>       etag: 'W/"2b-hGShxOkieaAVDloBubJVM+h58D8"',
>       date: 'Thu, 17 Dec 2020 11:07:30 GMT',
>       connection: 'close'
>     }
> ```
> 
> Any idea how to append Authorization to the headers?
> 
> I also tried .set(Authorization, 'abc123')

@AndonMitev I'm guessing you're using the [request package](https://github.com/request/).
If that's the case, I'd recommend you construct the request object before sending it, making your code as such:
```
const options = {
  uri: <YOUR_URL>,
  method: 'GET',
  headers: {
    'Auhorization': 'Bearer <TOKEN>'
  }
};
await request(options)
            .expect(({ headers }) => {
                console.log(headers);
            })
            .expect(HttpStatus.BAD_REQUEST);
```

**Comment by ekramteyeb** [comment]
> I'm trying to set header but is not part of the headers
> 
> ```
>  await request(app)
>             .get('/user/all')
>             .set({
>                 Authorization: 'abc123',
>             })
>             .expect(({ headers }) => {
>                 console.log(headers);
>             })
>             .expect(HttpStatus.BAD_REQUEST);
> ```
> 
> This is the headers object:
> 
> ```
>  {
>       'content-security-policy': "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
>       'x-dns-prefetch-control': 'off',
>       'expect-ct': 'max-age=0',
>       'x-frame-options': 'SAMEORIGIN',
>       'strict-transport-security': 'max-age=15552000; includeSubDomains',
>       'x-download-options': 'noopen',
>       'x-content-type-options': 'nosniff',
>       'x-permitted-cross-domain-policies': 'none',
>       'referrer-policy': 'no-referrer',
>       'x-xss-protection': '0',
>       'access-control-allow-origin': '*',
>       'content-type': 'application/json; charset=utf-8',
>       'content-length': '43',
>       etag: 'W/"2b-hGShxOkieaAVDloBubJVM+h58D8"',
>       date: 'Thu, 17 Dec 2020 11:07:30 GMT',
>       connection: 'close'
>     }
> ```
> 
> Any idea how to append Authorization to the headers?
> 
> I also tried .set(Authorization, 'abc123')

// if you setup ur server to response with a token after a login operation u can authorize the get/post individual operation as follow .N.B // token = a string sent back as response header to the browser by a server 
await request(app)
>             .get('/user/all')
>             .auth(token, {type:'bearer'} ) 
>               
>             })
>             .expect(({ headers }) => {
>                 console.log(headers);

**Comment by junajan** [comment]
> > > Note that you have to call `.set()` AFTER calling `.post()`, not before. For example:
> > > ```js
> > > request(app)
> > >   .set('Authorization', 'abc123') // DOES NOT WORK
> > >   .post('/api')
> > > 
> > > request(app)
> > >   .post('/api')
> > >   .set('Authorization', 'abc123') // Works.
> > > ```
> > 
> > 
> > It's TERRIBLE !!!
> > Suppose i have multiple routes to test, which all are protected by same authentication middleware ( using headers). This way, I have to set header independently for all of them!!
> 
> Well it would only make sense to do that since in a real-life scenario you are making separate HTTP Requests, each having its own separate Header. Unless I understood you wrong?

Sometimes - eg while running integration tests - it completely makes sense to set same headers for all requests.
In my case I would like to create a factory method which returns supertest agent with default headers but because headers are reseted when `.post()` is called, it is not easily possible..

**Comment by felixmosh** [comment]
It is possible by using the agent it self, and calling `auth` method, which defines a default set of headers

```js
import { agent as supertest } from 'supertest';
// ---------^ this is the important part, using the agent itself.
import app from './app';

agent = supertest(app);
const response = await agent.post('/api/auth/login', { username: 'tester', password: 'tester' });
agent.auth(response.accessToken, { type: 'bearer' });

// this request will include the Authorization header
agent.post('/api/customer/add', { name: 'foo' });
```

**Comment by camariana** [comment]
Peace, @vegaByte @felixmosh @thelebdev I have an internal server error with the following. Anyone knows why? Here is the repo https://github.com/camariana/fs-blog-list

`test('succeeds with valid data', async () => {
    const newBlog = {
      title: 'What we are living for',
      author: 'A. Camariana',
      url: 'camariana.gm',
      likes: 0,
    }

    await api
      .post('/api/blogs/')
      .set({ 'Authorization': 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhbWFyaWFuYSIsImlkIjoiNjBiYThjODQ0OWIzMjU0YWUzZDFiZDBmIiwiaWF0IjoxNjI0MzQ2Mjg4LCJleHAiOjE2MjQzNDk4ODh9.ruPKk293QDfxUq1emdVH0sbuJEhRrfY9q9jVllaMYPA' })
      .send(newBlog)
      .expect(200)
      .expect('Content-Type', /application\/json/)

    const blogsAtEnd = await helper.blogsInDb()
    expect(blogsAtEnd).toHaveLength(helper.initialBlogs.length + 1)

    const contents = blogsAtEnd.map(b => b.title)
    expect(contents).toContain(
      'What we are living for'
    )
  })`

**Comment by camariana** [comment]
> Separe the `request` logic from all your tests simulating supertest(url).method()
> 
> ```js
> const URL = `My Endpoint`;
> const TOKEN = 'Secret';
> 
> const hook = (method = 'post') => (args) =>
>   supertest(URL)
>     [method](args)
>     .set('Authorization', `Basic ${TOKEN}`);
> 
> const request = {
>   post: hook('post'),
>   get: hook('get'),
>   put: hook('put'),
>   delete: hook('delete'),
> };
> 
> export default request;
> ```
> 
> I dont touch my tests code

@vegaByte, How do you go about implementing this?

**Comment by technoknol** [comment]
> It is possible by using the agent it self, and calling `auth` method, which [defines a default set of headers](https://github.com/visionmedia/superagent/blob/3c9c0f7feef61328131ae43b06e628bce1c20c17/src/agent-base.js#L30)
> 
> Calling `agent.post` will set [these defaults](https://github.com/visionmedia/superagent/blob/master/src/client.js#L899)
> 
> ```js
> import { agent as supertest } from 'supertest';
> // ---------^ this is the important part, using the agent itself.
> import app from './app';
> 
> agent = supertest(app);
> const response = await agent.post('/api/auth/login', { username: 'tester', password: 'tester' });
> agent.auth(response.accessToken, { type: 'bearer' });
> 
> // this request will include the Authorization header
> agent.post('/api/customer/add', { name: 'foo' });
> ```

I'm getting this error: 
![image](https://user-images.githubusercontent.com/6429418/161390244-d34234e7-4195-4f0c-b79d-e67abe29976e.png)

Can anyone help here?

**Comment by mmamedel** [comment]
Why not using `Proxy`? Such as:
```typescript
const defaultAgent = new Proxy(supertest(app), {
  get: (target: any, name) => () =>
    target[name]().set({
      'Authorization': `Bearer ${defaultToken}`,
      'Accept': 'application/json',
    }),
})
```
Then you can use just as any agent:
```typescript
defaultAgent.get('url')
defaultAgent.post('url')
...
```
You can set any properties in the proxy.

**Comment by BugliL** [comment]
I have resolved with a simple monkey patching
```typescript
// ...

    beforeAll(() => {
      request = supertest(app.getHttpServer());
      // Next line is important or recursion hell will kill your code
      const originalMethod = request.patch;
      request.patch = (url: string, ...args) => {
        return originalMethod(url, ...args)
          .set('Content-Type', 'application/json')
          .set('X_CONNECTION_KEY', 'XXX');
      };
    });
    
// ...
```

**Comment by marvin-wtt** [comment]
I noticed a strange behavior today with a delete request:

This works:
```ts
request(app)
  .delete(`/resource/${id}`)
  .set({ Authorization: `Bearer ${token}` })
  .expect(204); // Passes
```

But this does not work:
```ts
const response = await request(app)
  .delete(`/resource/${id}`)
  .set({ Authorization: `Bearer ${token}` });

expect(response.statusCode).toBe(204); // Fails --> 401
```
What is the problem here?

**Comment by felixmosh** [comment]
calling delete before the set will execute the request before you set the header.

**Comment by marvin-wtt** [comment]
> calling delete before the set will execute the request before you set the header.

Thanks for your reply.  
How is it possible to set a header before calling delete?

The example in the README uses the GET verb, but the call is very similar:
```ts
describe('GET /users', function() {
  it('responds with json', async function() {
    const response = await request(app)
      .get('/users')
      .set('Accept', 'application/json')
    expect(response.headers["Content-Type"]).toMatch(/json/);
    expect(response.status).toEqual(200);
    expect(response.body.email).toEqual('foo@bar.com');
  });
});

**Comment by techrook** [comment]
how can i set authorization for API KEY ?

**Comment by TinNguyenWav** [comment]
> how can i set authorization for API KEY ?
Hopefully this can help you, @techrook 

`import supertest from "supertest"
import { REQRES_BASE_URI } from 'src/api/config/baseuri';
import { endpoints } from "src/api/services/endpoints";

const request = supertest(REQRES_BASE_URI)
const HEADER = {
    TOKEN: process.env.API_KEY
}
const token = "Your token string"

export const makeGETCall = async (endpoint: endpoints | string) => {
    return request.get(endpoint).set('Authorization', `Bearer ${HEADER.TOKEN}`)
    //OR
    /*
        return request.get(endpoint).set('Authorization', `Bearer ${token}`)
    */
}`

**Comment by KaKashi1210** [comment]
.env file
```js
TOKEN = 'averylongstring'
```

case 1:
```js
await api.post('/').set('Authorization ' ,'Bearer ${process.env.TOKEN') // this fails with 400 status code
```

case 2:
```js
const token = 'averylongstring'
await api.post('/').set('Authorization ' ,'Bearer ${token') // this pass
```

why is this happening

**Comment by vedantjangid** [comment]
> > ```js
> > await api.post('/').set('Authorization ' ,'Bearer ${process.env.TOKEN')
> > ```
> 
> Because in case 1 you have wrong syntax. You are missing backtics `` and one bracket `}` It should be like this:
> 
> ```js
> await api.post('/').set('Authorization ' ,`Bearer ${process.env.TOKEN}`)
> ```

.set("Authorization", `Bearer ${loginResponse.body.token}`) // Corrected here

**Comment by ihssandk** [comment]
> ```js
> .set('Authorization ' ,'Bearer ${token')
> ```

require('dotenv').config() in test file

**Comment by karocksjoelee** [comment]
Why is this closed ?.?
