### ISSUE TITLE
Add support for promises in `expect`

### ISSUE THREAD

**Issue by LegNeato** [visionmedia/supertest#401]
Right now, if you have a promise in `expect` (for, say, an async function) it will be run but errors will not be detected.

**Comment by LegNeato** [comment]
Pushed again to fix an issue with passing `expect()`s never calling the async resolver and timing out. Also added a test for the case.

**Comment by ianstormtaylor** [comment]
Would love to use this!

**Comment by selenium-tester** [comment]
Thank you @LegNeato!

**Comment by Fundebug** [comment]
@LegNeato It seems the problem is not solved. 

I‘m using supertest@4.0.2. 

I find that the AssertionError will not be detected when I use async/await in expect.

```javascript
 .expect(async res => {
     const orderId = res.body.orderId;
     const order = await Order.findById(orderId).lean(); // { price: 10 }

     order.should.deepEqual({
         price: 50
     });
 });
```

**Comment by gcherem** [comment]
@LegNeato, I'm afraid the problem is still there yet.

I also need to call an async method there too!

Is there a workaround for that? Thanks

**Comment by LegNeato** [comment]
I don't know, it could have regressed since this was landed years ago. I only use Rust these days so sadly can't help.
