### ISSUE TITLE
Not asking for the right endpoint when using japanese characters

### ISSUE THREAD

**Issue by Klauswk** [visionmedia/supertest#403]
Whatever i try to test and endpoint using an japanese character, the supertest seems to lose himself in the routing.

The Test:
```
        request(app)
            .get("/kanji/kanji/愛")
            .expect('Content-Type', "application/json; charset=utf-8")
            .expect(200)
            .end(function (err, res) {
                if (err) throw err;

                let responseObj = JSON.parse(res.text);
                expect(responseObj.Kanji).equal("愛");
                done();
            });
```

Throws: `Uncaught TypeError: Cannot read property 'header' of undefined` , and not even pass in the middleware asking for the endpoint.

If i ask for an not japanese character, the endpoint works just fine:

```
        request(app)
            .get('/kanji/kanji/123456')
            .expect('Content-Type', "application/json; charset=utf-8")
            .expect(400)
            .end(function (err, res) {
                if (err) throw err;

                let responseObj = JSON.parse(res.text);
                expect(responseObj.error).equal("Kanji must be an character");
                done();
            });
```

My project its open source, and can be found [here](https://github.com/Klauswk/KanjiRest), and the working endpoint [here](https://kanji-rest.herokuapp.com/api/kanji/kanji/%E6%84%9B)

Also, using the last release version of supertest

**Comment by pornel** [comment]
This is not a valid URL: `"/kanji/kanji/愛"`. URLs only allow certain ASCII characters. Kanji must be URL-encoded: '/kanji/kanji/%E6%84%9B'. Use `encodeURI()` function or similar.
