### ISSUE TITLE
Stop server after test when using promises

### ISSUE THREAD

**Issue by Levino** [visionmedia/supertest#405]
As far as I understand a call to "end" for the callback version of supertest does actually stop the server. Meanwhile it does not look like this has been implemented for the promise version. I am concerned about this because with ```mocha --watch``` on rerunning the tests they fail with an "EADDRESSINUSE" error.

So is there a way to take down the server after a test with the promise version? If not then this should probably added, maybe with a ```.stop()``` function or so.

**Comment by Levino** [comment]
Never mind, I was doing it wrong.

**Comment by nabilfreeman** [comment]
@Levino can you please explain what you were doing wrong? (if you remember)

**Comment by Levino** [comment]
@nabilfreeman No I do not remember. Please share some example that shows your issue and I will have a look.

**Comment by Levino** [comment]
Also something else to remember: Supertest can test an express app without starting a server! Maybe that is already enough?
