### ISSUE TITLE
.query : Array type problem

### ISSUE THREAD

**Issue by jy95** [visionmedia/supertest#407]
Hello,

I use your .query function (as explained here : http://visionmedia.github.io/superagent/#query-strings) and I found an issue : the array of int is parsed to not an array

The only workaround I found is to put them directly in url :
```js
request(app)
                .get(BASE_PATH + "/calls?callsIds=[1,2,125,777]")
                .query({
                    offset: 0,
                    limit: 10,
                    order: "ascending",
                    treated: true,
                    date: "2016-02-28"
                })
                .expect(200, done);
```
Anyway to fix it ? Seems the array type isn't supported ...

EDIT : also unable to pass object to url, again have to pass them directly in url

```js
request(app).get(BASE_PATH
 +"&extendTypes={\"phones\":true,\"plates\":true,\"subscriptions\":true}");
```

**Comment by ravichandranjv** [comment]
Any response to this issue ? Because I have opened one where .query does not pass parameter value to a get route as below:

var someValue='1234';

.get('/someRoute')
.query(someValue) nor 
.query({'someKey': someValue})

**Comment by xiaomai7758** [comment]
没有灵魂啊!express用的qs是支持数组的
