### ISSUE TITLE
[TypeError: (0 , _supertest2.default)(...).set is not a function]

### ISSUE THREAD

**Issue by selenium-tester** [visionmedia/supertest#412]
I'm running into this error and I'm not sure why. Why does something like this (pseudocode) work perfectly:

```
import test from 'ava';
import request from 'supertest';

test('Example POST', async t =>
{
    await request(url)
        .post(endpoint)
        .set(headers)
        .send(account)
        .then((response) =>
        {
            t.is(response.status, 404);
        })
});
```

But this does not:

```
import test from 'ava';
import request from 'supertest';

test('Example GET', async t =>
{
   await request(url)
        .set(headers)
        .then((response) =>
        {
            t.is(response.status, 404);
        })
});
```

Am I missing something obvious about how to use supertest to structure a GET call that is different from a POST?

**Comment by selenium-tester** [comment]
I worked it out. I was thinking I could structure the GET with an absolute URL (i.e, http://localhost/foo) the way curl does it, but supertest apparently needs it in the form of:

```
request('http://localhost')
    .get('/foo');
```

Which makes sense now given how ```.post``` is structured the same way. But according to the superagent docs we SHOULD be able to support absolute urls...

Apologies for the issue clutter.

**Comment by mikegleasonjr** [comment]
This is unfortunate that in superagent it works both ways (`request.get(fullUrl)` and `request(base).get(path)` and not in supertest.

Really? Now I have to parse my url, split the path from the base?
