### ISSUE TITLE
Error running Supertest on multi-process application

### ISSUE THREAD

**Issue by jwerre** [visionmedia/supertest#414]
I've noticed I'm not able to run supertest on a multi-process application. Has anyone found a workaround for this:

### app.js

```
var os = require('os'),
	cluster = require('cluster'), 
	express = require('express');

if (cluster.isMaster) {
	totalCPUs = os.cpus().length;
	forks = 0;
	while (forks < totalCPUs) {
		cluster.fork();
		forks++;
	}
	cluster.on('exit', function(worker) {
		console.error("Cluster worker " + worker.id + " exited unexpectedly.");
		return cluster.fork();
	});
} else {
	app = express();
	// ...
	app.listen(app.get('port'), function() {
		return console.log("started on port " + app.get('port'));
	});
	module.exports = app;
}
```

### test/app.js

```
var should = require("should"),
	request = require('supertest'),
	app = require('../app');

describe("APP", function() {
	var accessToken, refreshToken;
	accessToken = null;
	refreshToken = null;
	it("should load", function(done) {
		request(app)
		.get("/login")
		.expect(200)
		.end(function(err, res) {
			should.not.exist(err);
			should.exist(res.body);
			return done();
		});
	});
});

```

### result

```
mocha test/app.js        


  APP
    1) should load
  0 passing (10ms)
  1 failing

  1) APP should load:
     TypeError: app.address is not a function
      at Test.serverAddress (node_modules/supertest/lib/test.js:55:18)
      at new Test (node_modules/supertest/lib/test.js:36:12)
      at Object.obj.(anonymous function) [as post] (node_modules/supertest/index.js:25:14)
      at Context.<anonymous> (test_back/api.coffee:19:27)

```

**Comment by agauniyal** [comment]
@jwerre it's not multithreaded, but different instances of your apps across multiple processes.

**Comment by skehlet** [comment]
Yes, it's multi-process not multi-threaded, but the problem is valid. I think it might be `cluster` mucking with `.address`. 🤔

**Comment by agauniyal** [comment]
Don't know much about the internals of supertest and all things related to it, but take a look at app.js `if/else` conditions.

**Comment by agauniyal** [comment]
Not sure if relevant, but take a look at app.js `if/else` conditions.

**Comment by skehlet** [comment]
I switched to old school [`fork`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) instead of `cluster` (I'm writing a multiprocess mocha test runner) and now the issue I had similar to this one is gone. Maybe supertest could accommodate this weirdness with cluster better but I wouldn't blame it if it didn't. Good luck!
