### ISSUE TITLE
 request(...).serialize is not a function

### ISSUE THREAD

**Issue by apedyashev** [visionmedia/supertest#417]
I don't want my request body to be serialized so I use the superagent's `.serialize()` method 

```
return request(sails.hooks.http.app)
     .serialize((data) => data)
     .put(`/subscriptions/${createdSubscription.id}`)
     .set('Authorization', authHeader)
     .send(null)
     .expect(400);
```

but I get this error
` request(...).serialize is not a function`

if I call `.serialize()` after `.put()` then it doesn't throw this error, but null in the request body gets transformed into an empty object.

How can I send null with PUT request?

**Comment by JoshuaBaert** [comment]
@rimiti Is there any plan to add this?
