### ISSUE TITLE
Inconsistent response body.

### ISSUE THREAD

**Issue by d30jeff** [visionmedia/supertest#424]
In my response code, I have this line that checks `totalRecipients` which is **40**

`assert.equal(40, res.body.messageBatches[0].totalRecipients)`

When I run the test, I sometimes get between 36-39. Failing my test.

I have used **postman** to verify that I indeed have 40.

There's no `DELETE` on my test so it shouldn't be a factor.

Many thanks

**Comment by mikelax** [comment]
This sounds like an issue with the test fixtures or data, not specifically related to supertest functionality.
