### ISSUE TITLE
Simulate connection broken 

### ISSUE THREAD

**Issue by wexoni** [visionmedia/supertest#426]
I would like to know is it possible to simulate connection loss using supertest?

I have some file upload feature, and I use multiparty to handle it.

In my controller, I have temporarily added a:

```
//Simulate request aborted
                setInterval(function() {
                    request.emit('aborted');
                },200);
```

I use supertest like this:

```
it('should upload image with name for user', (done) => {
            request(app)
                .put('/api/v1/me/image/image-test-name.jpg')
                .attach('file', 'test/fixtures/images/demo.jpg')
                .set(constants.HEADERS.USER_1)
                .expect(() => {                    
                })
                .expect(200, done);
        });
```

setInterval makes it work for me, but it would be ideal if I could do it using supertest.

**Comment by lionello** [comment]
Using ExpressJS, I ended up doing `setTimeout(() => req.socket.destroy(), 100)`
