### ISSUE TITLE
superagent "write()" does not return "this"

### ISSUE THREAD

**Issue by themez** [visionmedia/supertest#433]
Hi, when I want to test an API which accepts binary request, the test failed with `.write().end is not a function`
```
request(app)
  .post(url)
  .write(buffer)
  .end(...)
```
Then I checked superagent code, found `write` function does not return `this`, it's not hooked.
```
Request.prototype.write = function(data, encoding){
  var req = this.request();
  if (!this._streamRequest) {
    this._streamRequest = true;
    try {
      // ensure querystring is appended before headers are sent
      this._appendQueryString(req);
    } catch (e) {
      return this.emit('error', e);
    }
  }
  return req.write(data, encoding);
};
```
Can this case be fixed?

**Comment by perqin** [comment]
According to the jsdoc:

```
/**
 * Write raw `data` / `encoding` to the socket.
 *
 * @param {Buffer|String} data
 * @param {String} encoding
 * @return {Boolean}
 * @api public
 */

Request.prototype.write = function(data, encoding){
...
```

This API does return boolean instead of `this`. I think this is a API design issue of superagent, but I figure out a workaround:

```

test('Integration test', async () => {
  const req = request(app.callback()).post('/sync/push')
  req.type('application/octet-stream')
  req.write(fs.readFileSync(path.resolve(__dirname, './push-0.bin')))
  const res = await req
  expect(res.status).toBe(200)
})
```

**Comment by yukw777** [comment]
@perqin Does your code actually work? I have an express server using `bodyParser.raw()` to handle the binary data, and I used your code to send over a `Buffer` of binary data like that, but the server doesn't seem to receive anything.

**Comment by vitalyster** [comment]
Have the same issue and @perqin example does not work. Is it possible to document correct example for binary post?
