### ISSUE TITLE
How to pass method string

### ISSUE THREAD

**Issue by Overdrivr** [visionmedia/supertest#434]
Is it currently possible to pass the HTTP method with a string instead of the `post(..)` `get(..)` apis ? Similar to what can be done in [superagent](http://visionmedia.github.io/superagent/#request-basics)

**Comment by bali182** [comment]
I'm not a maintainer, was just wondering about this myself. If you look at `index.js` it constructs tests using an app, a request method and an url. Based on this you could import the `Test` class directly and use it with the http verb as a string:

```js
import { Test } from 'superagent'
import app from './app'

new Test(app, 'get', '/foo')
  .expect(200)
  // ...
```

**Comment by mikelax** [comment]
@Overdrivr  to start a `Test` with supertest you must start the chain with a VERB, such as get, post, delete, etc.
