### ISSUE TITLE
Is this project really maintained?

### ISSUE THREAD

**Issue by vajahath** [visionmedia/supertest#464]
This is an awesome library, without a question. It's monthly downloads crosses 1.2M.
Why this project is badly abandoned?
25 PRs and 136 issues.
6 issues opened last month. (see!)
But last commit was on 30 Jan 2017!

If the current maintainers are not interested in maintaining this project, please in open an issue like `looking for maintainers`.

#383

**Comment by 1999** [comment]
@tj there were 52 contributors and 5 npm users who published this package. Is it possible to just transfer ownership (or at least the merge access rights) to some of them?

**Comment by tj** [comment]
happy to provide access if anyone wants it

**Comment by rimiti** [comment]
27 Pull request in pending... If you need help to maintain this projet, contact me.

**Comment by mikelax** [comment]
Hey all, I was working on taking on some PRs and small updates to this package but had gone quiet last year. I'm back, I'll try to get the v3.1 release out, as that is mostly set and contains a couple of simple PRs and updates. 

Where I could really use some help is in triaging the tickets that come in, most of them are simple usage questions and not really issues. 
A large percentage of the PRs are also invalid and old, and should be closed.

**Comment by chrisveness** [comment]
@mikelax great news! I'm currently referencing #297 directly from the https://github.com/mikec/supertest PR repo – I would love to see that merged into canonical.
