### ISSUE TITLE
Attach() should put files on request.files?

### ISSUE THREAD

**Issue by wlepinski** [visionmedia/supertest#47]
Hello, this is more a doubt than a issue.

I'm using the method attach() to simulate a file upload to a express middleware. I was expecting that the request.files would be filled with the information of the attached file, but instead I'm receiving an undefined variable on request.

Am I doing something wrong?

``` javascript
request(app)
      .post('/test')
      .attach('image', __dirname + '/fixtures/fatcat.jpeg')
      .expect('Content-Type', /json/)
      .expect('Content-Length', '15')
      .expect(201)
      .end(function(err, res){
        if (err) throw err;
        done();
      });
```

middleware

``` javascript
return function handler(req, res, next) {
      console.log(req.files); // returns undefined :(
}
```

Thanks in advance.

**Comment by SteveNewhouse** [comment]
Having same problem... let me know if you sorted it @wlepinski

**Comment by wlepinski** [comment]
Wow, this issue very old, @SteveNewhouse I really don't remember what I did so try what @gjohnson said. Good luck.

**Comment by calidion** [comment]
how to send image files array and with many fields?

**Comment by SkateFreak** [comment]
@calidion 
+1 how to send image files array and with many fields?

**Comment by dennishu001** [comment]
You can attach files just as OP described. The problem is that the multipart parser is no longer included in express bodyparser. You need to use a seperate package such as multer to handle multipart/form-data. I just found this out after upgraded my project to express 4.x.

**Comment by SkateFreak** [comment]
my solution was to user```.field()```s along with ```.attach()```
(if i remember correctly i even got a warning sometime that ```send()``` and ```.attach()``` don't work together)

i've encountered so many issues with multer and multipart form data, so i'd rather handle ```base64``` via json

**Comment by radiumrasheed** [comment]
> my solution was to use`.field()`s along with `.attach()`
> (if i remember correctly i even got a warning sometime that `.send()` and `.attach()` don't work together)
> 
> i've encountered so many issues with multer and multipart form data, so i'd rather handle `base64` via json

```javascript
      return request
        .post('/api/v1/client/1/progress_note')
        .field('answers', progressNoteData.answers)
        .field('duration', progressNoteData.duration)
        .field('templateId', progressNoteData.templateId)
        .field('service', progressNoteData.service)
        .field('service_time', progressNoteData.service_time)
        .attach('attachment', 'test/mock-data/sample-image.png')
```

**Comment by dash7ou** [comment]
@gjohnson

**Comment by dash7ou** [comment]
@SteveNewhouse

**Comment by tobslob** [comment]
@radiumrasheed `.filed` only works if the field is a `string`, how can a field of an array or object be handled? I tried creating multiple fields with the same name, but  throws error

**Comment by tobslob** [comment]
> @radiumrasheed `.filed` only works if the field is a `string`, how can a field of an array or object be handled? I tried creating multiple fields with the same name but throws an error

This works by `stringify` the field

**Comment by radiumrasheed** [comment]
yes, you need to stringify the array

**Comment by lcundiff** [comment]
Adding fields didn't seem to change how attachment was handled for me. I still wasn't able to see it when printing out req.files or req.file. 

If someone is still looking for a solution, I used "form.parse" as part of multiparty library on my backend (nodejs) to get the files object from req, in which took me forever to realize that the file was stored on the attachment field on "files" as you can see below. 

```
exports.nodeFunction = function (req, res) {
    var form = new multiparty.Form({
        uploadDir: 'app/tmp'
    });
    form.parse(req, function (err, fields, files) {
        var file = files.file ? files.file[0] : files.attachment[0]; 
        // when uploaded on front end, files.file has the file, but files.attachment holds the file when using supertest in mocha. 
    });
```

Here's my test function as well: 
`        describe('POST', function () {
            it('Should upload file', async function () {
                    const res = await request(app).post(url) // request = require('supertest') 
                    .attach('attachment', path.resolve(__dirname, filename)) // using "path" library 
                    .expect(200) 
            });
        });`

**Comment by MikeDabrowski-EQM** [comment]
I have similar setup in two projects. One works the other does not. 

Test:
```
it('updates avatar', async () => {
    const fileName = 'avatar.jpeg';
    const fileMock = Buffer.from('Test file content', 'utf-8');

    response = await requestWithSupertest
      .patch(`/v2/avatars`)
      .field('file', fileMock)
      .attach('file', fileMock, {
        fileName, contentType: 'image/jpeg',
      });

    expect(response.status).toEqual(200);
    expect(response.body.url).toBeTruthy();
  });
```
ts-rest route
```
updateAvatar: {
    'PATCH /v2/avatars': {
      handler: (...args) => {
        console.log(args); // req does not have files
        return updateAvatar(...args);
      },
      middleware: [multer({
        storage: multer.memoryStorage(),
        fileFilter (_: e.Request, file: Express.Multer.File, callback: multer.FileFilterCallback) {
(doesnt get called)
          if (!['image/jpeg', 'image/png', 'image/jpg'].includes(file?.mimetype)) {
            throw new errors.UnsupportedMediaType({
              path: 'mimetype',
              message: `File mimetype "${file.mimetype}" is not allowed`
            });
          }
          callback(null, true);
        }
      }).single('file')]
    }
  }
```
