### ISSUE TITLE
How to Add "apiGateway" To Request?

### ISSUE THREAD

**Issue by JimTheMan** [visionmedia/supertest#476]
Hi, great library, but I am having some trouble.

I am creating a backend service that runs as a AWS Lambda function and uses the 'aws-serverless-express' library for handling routing. I pull the query paramters off of the incoming request by looking at 'req.apiGateway.event. My soruce code looks something like this: 

```
app.get('/', function (req, res) {

  const args = req.apiGateway.event.queryStringParameters || req.apiGateway.event
   ...

}
```

In my supertest code I tried doing this:

```
request.get('/?email=derp@derp.com').expect(200).end(function (err, result) {

      done(err)
    })
```

I've also tried using the supertest functions "send" and "query", but none of them seems to add the properties in the correct place. 

When I try to test this with supertest I always get the error, "cannot read property event of undefined". 

Is there some way for me to add these properties with my supertest get request? Thanks!

**Comment by JimTheMan** [comment]
anyone?

**Comment by mikelax** [comment]
I am not too familiar with that package, but are you using [the middleware](https://github.com/awslabs/aws-serverless-express#getting-the-api-gateway-event-object) as per their docs. I don't think this is an error or bug with supertest. 

You can use any [existing superagent methods](http://visionmedia.github.io/superagent/#-get-requests) to construct the request and body needed by that package.

**Comment by JimTheMan** [comment]
@mikelax As I stated in the original post I already tried to use "send" and "query" existing superagent methods which did not work as expected with aws lambda serverless. What other methods are you referring to??

Btw it's kind of rude to close someone's issue without offering any useful advice whatsoever besides "rtfd".
