### ISSUE TITLE
JSON object duplicated in response

### ISSUE THREAD

**Issue by GiridharKarnik** [visionmedia/supertest#482]
I was using Supertest@3.1.0 and found a strange bug (at least I think so).

I have a simple node-express endpoint which spits out a json

```javascript
userRoute.post(499).send({  
     "hello": "hello"
});
```

I have written a test to assert this endpoint in supertest

```javascript
request(api)
    .post("/user/signIn")
    .set('Accept', 'application/json')
    expect(499, done)
    .end((err, res) => {
    if(err) {
             let error = "Uncaught error while testing " + err;
             console.log(error.red);
             return done(err);
       }
    done();
});
```

I get the following error wherein the response has the following json object

`{"hello":"hello"}{"hello":"hello"}`

![screen shot 2018-05-17 at 7 50 44 pm](https://user-images.githubusercontent.com/17564776/40183513-ac1bb90c-5a0b-11e8-82e6-36bba011d096.png)

The same API is behaving well with the test code written in `chain` and `chai-http`.

**Comment by mikelax** [comment]
I'm not exactly sure what format your post endpoint is using, but you might need to use `res.json` instead of `send`. 

Did you try this:
```javascript
app.post('/user/signIn', function(req, res) {
  res.status(499).json({ hello: 'hello' });
});
```

I don't think this is an error with supertest.
