### ISSUE TITLE
Inconsistent data type behavior of expect(object)

### ISSUE THREAD

**Issue by awvalenti** [visionmedia/supertest#486]
Consider this test:
```javascript
request(url).get('/url').expect({ a: 1, b: 2});
```

This production code (both properties incorrect: a is string instead of number and b is 3 instead of 2)
```javascript
res.status(201).json({a: '1', b: 3});
```
produces the following (correct) test result:

```
Error: expected { a: 1, b: 2 } response body, got { a: '1', b: 3 }
      + expected - actual

       {
      -  "a": "1"
      -  "b": 3
      +  "a": 1
      +  "b": 2
       }
```

However, this production code (a is still a string instead of number and b is correct)
```javascript
res.status(201).json({ a: '1', b: 2 });
```

produces

```
1 passing (5ms)
```

In other words, current (incosistent) behavior is:
- If all properties are ```==```, ok!
- If they are not ```==```, compare them using ```===``` to show the result

The behavior should be the same in all cases. Presumably, only ```===``` should be used for comparison, producing the same result as ```deepEqual``` method from ```should``` library.

Temporary solution is to do:
```javascript
.expect(res => res.body.should.deepEqual({ a: 1, b: 2 }));
```

**Comment by mikelax** [comment]
@awvalenti  yes that is currently a known limitation. The `expect` function is checking the response body using `assert.deepEqual`, which for primitives (of the object) does use `==`. 

I think the correct answer is to change [this line](https://github.com/visionmedia/supertest/blob/master/lib/test.js#L201) to use `.deepStrictEqual` instead.
