### ISSUE TITLE
Support for JSON merge-patch

### ISSUE THREAD

**Issue by t3hmrman** [visionmedia/supertest#498]
It looks like super agent doesn't support [JSON merge-patches](https://tools.ietf.org/html/rfc7386) with `Content-Type: application/merge-patch+json`. When I try to `send(...)` a JSON value it comes out on the other side empty:

```js
    const req = request(app)
        .patch(url)
        .set("Content-Type", "application/merge-patch+json")
        .send(entity);
        .expect('Content-Type', /json/)
        .expect(200);
```

To reiterate, on the server side, `req.body` is actually empty.

I haven't looked at the code but if I had to guess I'd gues sthat `send(..)` is doing some conversion stuff depending on what `Content-Type` is set to, which makes sense, but it would be nice in general if I could turn it off, or specify what the body is concretely to avoid this problem.

**NOTE** this issue was originally [incorrectly filed on `superagent`](https://github.com/visionmedia/superagent/issues/1404)

**Comment by jonathansamines** [comment]
@t3hmrman Did you tried to reproduce it with `superagent` alone? It doesn't looks like something this library would cause as it is a small layer on top of superagent which just adds some useful utilities.

**Comment by jonathansamines** [comment]
@t3hmrman supertest only uses your express application to determine in which port is your app running (randomly generates a new port allocation using app.listen), so that you can use relative urls without having to explicitly tell supertest where your application lives in.

**Comment by t3hmrman** [comment]
Ahhhh OK  I never looked into it properly and just assumed supertest did something more with the app not just running it on a random port... I'm going to close this ticket and find some time to make a proper testcase for `superagent`
