### ISSUE TITLE
expect array in any order

### ISSUE THREAD

**Issue by Billy-** [visionmedia/supertest#502]
I have something similar to this:

```js
describe('list', () => {
  it('returns the contents of the database', async () => {
    await request
      .get('/')
      .expect(200)
      .expect(expectedItems)
  })
})
```

I don't care about the order (in this test) - however the test will fail if the objects in the array are not in the same order as they are in `expectedItems`. Is there any way to achieve this out the box or should I implement a custom expect function?

TIA

**Comment by mikelax** [comment]
hello @Billy- The `expect` function is using the function `assert.deepEqual` to test the response body and the `expectedItems` array. `deepEqual` only returns true if the arrays are the same, and in the same order. If you don't care about order then you will need to implement a custom expect function.
