### ISSUE TITLE
Using `.host` method results in request not going to unit under test

### ISSUE THREAD

**Issue by selaux** [visionmedia/supertest#514]
When using the `.host(hostName)` method to set a custom host header, the request actually goes out to the IP obtained by resolving the hostName passed to the method. I would expect the request to still go to the unit under test and just having a different hostname.

This is also reflected in the tests [here](https://github.com/visionmedia/supertest/blob/master/test/supertest.js#L876). The tests acually end in an error because the request goes out to `http://something.test/`, where resolving the name fails. So it is unclear to me if this is expected behavior or not. The better behavior to me would be to still request `127.0.0.1` and set the `Host` header manually. I created a PR that implements this behavior: https://github.com/visionmedia/supertest/pull/515

Simple example to reproduce (will hang infinitely when trying to request `http://google.com:xxxxx/`) instead of passing:

```
const request = require('supertest');
const express = require('express');

const app = express();
const agent = request.agent(app);

app.get('/', function (req, res) {
    res.send();
});

agent
    .host('google.com')
    .get('/')
    .expect(200)
```

**Comment by WojciechRydel** [comment]
Hi! I would like to kindly ask about status of the issue - it would be great tho have the possibilty to change a hostname.

**Comment by niftylettuce** [comment]
https://github.com/visionmedia/supertest/releases/tag/v6.0.0
