### ISSUE TITLE
How to set query params

### ISSUE THREAD

**Issue by willxd42** [visionmedia/supertest#521]
please how do I send query params so my test doesn't fail

**Comment by jonathansamines** [comment]
I would recommend you to read the [superagent](https://visionmedia.github.io/superagent/) docs. Most of it's public API is available to supertest. You could probably do something like:

```js
   request('http:///the-url.com/some-path').query({ key: 'value' })
```

**Comment by bluenote10** [comment]
Is there an issue with the typescript typings of supertest?

![image](https://user-images.githubusercontent.com/3620703/77322762-82d51e80-6d14-11ea-9ad9-0c9eca993018.png)

**Comment by jimbo8098** [comment]
Just in case anyone else is wondering, you now nee to query this as:

```
request('http:///the-url.com/some-path')
    .get("/")
    .query({ key: 'value' })
````

**Comment by nguyenminhphu2809** [comment]
I can't access /list_questions_user/:type by declaring /list_questions_user/tuition . Can anyone help me
