### ISSUE TITLE
.query works in express app but not in express router

### ISSUE THREAD

**Issue by alexalexson143** [visionmedia/supertest#526]
Hi,

When testing my express.Router(), I wanted to pass query strings as shown below:
```javascript
  it("blah2", done => {
    request(router) // USE ROUTER - NO QUERY OBJECT
       .get('/item')
       .query({ query: 'Manny' })
       .query({ range: '1..5' })
       .query({ order: 'desc' })
       .then(res => {
         done()
       })
       .catch(() => {
        done()
       })
  })
```

When I console.log(req.query) the result is undefined. However When I use app instead:
```javascript
  it("blah", done => {
    request(app) // USE APP - WITH QUERY OBJECT
       .get('/item')
       .query({ query: 'Manny' })
       .query({ range: '1..5' })
       .query({ order: 'desc' })
       .then(res => {
         done()
       })
       .catch(() => {
        done()
       })
  })
```

The req.query object exists.

This is how I initialized my router and app.
```javascript
const router = express.Router()
const app = express()
router.use((req, res, next) => {
  Object.setPrototypeOf(req, app.request)
  Object.setPrototypeOf(res, app.response)
  req.res = res
  res.req = req
  next()
})
app.use(router)
```

**Comment by jonathansamines** [comment]
@alexalexson143 I don't think that would work. Just the following are valid values when creating a new agent:

+ A express application
+ A node http server
+ An absolute url to the server

In either case I can tell you, that `supertest` is not meant to test your application by using any express internal, but rather by communicating to it through http. 

Hope that helps.

**Comment by alexalexson143** [comment]
Ok thanks for clearing that up!
