### ISSUE TITLE
Need to support `JSONP` response

### ISSUE THREAD

**Issue by fengmk2** [visionmedia/supertest#53]
rt

**Comment by mitchallen** [comment]
This is how you can test JSONP:

`    it('jsonp callback', done => {
        var testHost = "http://localhost:3000",
            cbName = "foo",
            testUrl = "/jsonp",
            testObject = { 
                "cb": cbName
            },
            expectedText = '/**/ typeof foo === \'function\' && foo({"message":"Hello World!","type":"jsonp"});';
        request(testHost)
            .get(testUrl)
            .query(testObject)
            .expect('Content-Type', /javascript/)
            .expect(200)  
            .end(function (err, res) {
                should.not.exist(err);
                should.exist(res);
                console.log(res.text);
                res.text.should.containEql(cbName);
                res.text.should.eql(expectedText);
                done();
            });
    });`

Example Express App:

`"use strict";

var express = require('express'),
    parser = require("body-parser"),
    app = express(),
    port = 3000,
    payload = { message: 'Hello World!' };

app.set('jsonp callback name', 'cb');
app.use(parser.json());

app.get('/json', function (req, res) {
    payload.type = 'json';
    res.json(payload);
})

app.get('/jsonp', function (req, res) {
    payload.type = 'jsonp';
    res.jsonp(payload);
})

app.listen( port, function () {
  console.log(`Example app listening on port ${port}!`);
})`

**Comment by AlexSlusarenko** [comment]
Hi @mitchallen, 
but what if expected content type header is `application/json` and response type `jsonp`, then supertest tries to parse response with json parser and fails. Maybe to add ability to choose parser, like: 
```
Request.prototype.parser = function(parser) {  // text (jsonp can be an alias)
// some parser string validation
this._parser = exports.parse[parser]
return this;
};
```
