### ISSUE TITLE
Update superagent dependency to v4.1.0

### ISSUE THREAD

**Issue by RobertDiebels** [visionmedia/supertest#549]
I'd like to suggest a version bump to 4.1.0 of superagent.

Version 4.1.0 contains a new feature which allows "Ignoring broken/insecure HTTPS on localhost" through a call to `.trustLocalhost()` this would be incredibly useful for testing purposes.

**Comment by rimiti** [comment]
Is anyone could upgrade superagent ? I'm currently busy on others projects, but I can provides some help if needed.

**Comment by RobertDiebels** [comment]
@rimiti I could create a PR but I don't know the ramifications of bumping the superagent version.

**Comment by rimiti** [comment]
You've to try to run the tests to know if there are regressions. ;)

**Comment by RobertDiebels** [comment]
Can someone look at the above merge-request? Would be great to get this in as soon as possible.

**Comment by gjohnson** [comment]
@RobertDiebels looking into it. I need to look at what # #534 was all about first.

**Comment by gjohnson** [comment]
In master
