### ISSUE TITLE
How to use supertest on node http servers, eg. http/2, I get 'Cannot read property 'address' of undefined'

### ISSUE THREAD

**Issue by desmap** [visionmedia/supertest#552]
Using koa and to get my app tested, I need to `module.exports` my app and then `request(app.listen())` in my test file to get it tested.

However, I couldn't get it to work when I `module.exports` the node http-servers on custom ports, e.g.:
```
module.exports = require('http2').createSecureServer({
  key: ...
  cert: ...
}, app.callback()).listen(process.env.PORT || 6443)
```
I get always 
```
  var addr = app.address();
                 ^

TypeError: Cannot read property 'address' of undefined
  at Test.serverAddress (/home/.../supertest/lib/test.js:55:18)
```
This is important because I redirect every non-http2 request in my middlewares. I could comment this out for testing but I guess that's not the purpose of testing.

The same applies for https.

**Comment by desmap** [comment]
Got it working and closing.

**Comment by olaven** [comment]
@desmap 👋 Would you mind sharing your solution? 
I'm asking as it would be helpful for myself and others finding this thread, struggling with similar issues. 

Have a nice day!
