### ISSUE TITLE
Setting request properties

### ISSUE THREAD

**Issue by AnoushSim** [visionmedia/supertest#564]
Hi! 
How can I set request property such as req.user ? It is for authenticated users. In beforeAll method I access the authenticated user and I want to pass it as request argument  in my tests.

**Comment by EsaNuurtamo** [comment]
Exactly the same issue. I want to manipulate req - object directly is there a way to do this?

**Comment by AnoushSim** [comment]
@EsaNuurtamo I solved this problem.... in set method I set my wanted property as header and then in function set req.prop to that header prop. Smth like this:
if(process.env.NODE_ENV === 'test') {
      req.user = req.headers.user
}

**Comment by rimiti** [comment]
Thank you @AnoushSim for the sharing of the solution.

**Comment by crysfel** [comment]
@AnoushSim thanks fo this solution, it's a bit hacky but it works
