### ISSUE TITLE
 TypeError [ERR_UNESCAPED_CHARACTERS]

### ISSUE THREAD

**Issue by renehauck** [visionmedia/supertest#570]
I'm trying to test an Api, but for some reason I get the error with a put method (other tests has no error with supertest):

```
const path = '​/api/v1/customerservices/' + serviceId.toString();
    return request(app.getHttpServer())
      .put(path)
      .set("authorization", apiKey)
      .send(serviceUpdateDTO)
      .expect(200)
      .then((value) => {
```

this is the error:
```
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

      132 |       .send(serviceUpdateDTO)
      133 |       .expect(200)
    > 134 |       .then((value) => {
          |        ^
      135 |         const tmpService: CustomerserviceDto = value.body;

```
and the path value:

![Path](https://user-images.githubusercontent.com/3898144/55724757-60b39500-5a0c-11e9-86f2-0c51900529f4.png)

I also tested the endpoint with Postman and there is no error. Is this a bug or did I do something wrong?

Thank you

**Comment by jonathansamines** [comment]
@renehauck I haven't actually tested if the `serviceId` value has some value not properly encoded. What is usually different on clients such as postman, is that they url-encode the whole url. Have you tried to use `encodeURIComponent()` over the `serviceId` value before appending it to the URL?

**Comment by rimiti** [comment]
@renehauck  You just need to encode your url / params as @jonathansamines said. 

I close this issue, have a good day.
