### ISSUE TITLE
how to set a proxy

### ISSUE THREAD

**Issue by angelochen960** [visionmedia/supertest#60]
following code does not work:

var request = require('supertest');
var url = '192.168.254.121';
var proxy = 'http://127.0.0.1:8888';

request = request(url)

request.get( proxy + '/verify?user=sample')
  .set('Host', "192.168.254.121")
  .set('Port', 8000)
  .end(function (res) {
  })

**Comment by peidong-hu** [comment]
any answer on this issue. I have the same problem with supertest to use http_proxy env var to run test

**Comment by RudyLu** [comment]
You may refer to the following as a temporary fix.
https://github.com/TooTallNate/superagent-proxy/issues/13#issuecomment-193624039

**Comment by tauheedkhan** [comment]
use supertest with proxy https://www.npmjs.com/package/supertest-with-proxy
