### ISSUE TITLE
Is it possible to group commonly-used chained methods together?

### ISSUE THREAD

**Issue by pcraig3** [visionmedia/supertest#606]
Hi everyone,

Sorry if this is a noob question with really obvious solution, but humour me if so.

Briefly, we're modifying some unit tests to account for passing in a CSRF token. It's working just fine but there's a lot of copy+paste.

Here's the code for one test:

```js
const response = await request(app)
        .post('/login')
        .set('Cookie', cookie)
        .send({ _csrf: csrfToken, other: 'value' })
```

All of our unit tests now need the `set` call and the `send` call where we set the `_csrf` value.

It would be good if we could group together some of those chained methods, more or less like this:

```js
const postWithCSRF = url => {
        ????? 👇 not sure how to do this
        return this.post(url)
        .set('Cookie', cookie)
        .send({ _csrf: csrfToken })
}

const response = await request(app)
        .postWithCSRF('/login')
        .send({ other: 'value' })
```

Is there a relatively straightforward way to do this that I haven't thought of, or is this meddling with core library things that we shouldn't be meddling with? 

(And I know we could turn off CSRF for tests, but this must be a general-enough problem.)

**Comment by jonathansamines** [comment]
@pcraig3 Yes, you could try using a [superagent plugin](https://github.com/visionmedia/superagent#plugins) for that. 

See https://github.com/visionmedia/supertest/issues/579#issuecomment-502714733

**Comment by rimiti** [comment]
I close it.

Thanks @jonathansamines and @pcraig3  for your contribution. 🙏
