### ISSUE TITLE
[BUG] Koa2 server: TypeError: app.address is not a function

### ISSUE THREAD

**Issue by tjx666** [visionmedia/supertest#613]
repository address: [coo-server](https://github.com/tjx666/coo-server)

![Snipaste_2019-12-19_19-57-42](https://user-images.githubusercontent.com/41773861/71171898-d3faef80-2299-11ea-942b-27b2f9fa6e54.png)

**Comment by bmuenzenmeyer** [comment]
@tjx666 how did you fix this?

**Comment by bfc846958672** [comment]
```
const app = require('./app');
const server = app.listen();
const request = require('supertest').agent(server);
```

look this : https://github.com/koajs/examples/blob/master/hello-world/test.js

**Comment by tjx666** [comment]
@bmuenzenmeyer just as @bfc846958672 describled

**Comment by tjx666** [comment]
You can also take a look at my koa boilerplate solution:
[https://github.com/tjx666/koa-restful-boilerplate/blob/master/src/index.js#L24](https://github.com/tjx666/koa-restful-boilerplate/blob/master/src/index.js#L24)
[https://github.com/tjx666/koa-restful-boilerplate/blob/master/test/global.test.js#L52](https://github.com/tjx666/koa-restful-boilerplate/blob/master/test/global.test.js#L52)
