### ISSUE TITLE
With http2 "socket hang up"

### ISSUE THREAD

**Issue by crystalfp** [visionmedia/supertest#617]
I'm using supertest on Windows 10 and node  12.14.1 with great satisfaction.
However, if I switch my server to http2 all tests fail. They prints only `socket hang up` and nothing more. My server is Koa and tests are written with typescript. Here is an excerpt:
```
import http2 from "http2";

const app = new Koa();
const options = {
	key:  fs.readFileSync(path.join(__dirname, "cert", "privkey.pem")),
	cert: fs.readFileSync(path.join(__dirname, "cert", "cert.pem"))
};

const server = http2
			.createSecureServer(options, app.callback())
			.once("error", handleServerErrors)
			.listen(3111, () => runApp("https"));

request = supertest(server);
```
Any ideas? Everything runs smoothly if I use http and createServer()

Thanks!
mario

**Comment by crystalfp** [comment]
Someone suggested to use `.trustLocalhost()` from superagent, but I don't know where to attach it.

**Comment by lddubeau** [comment]
I'm using fastify and ran into the same problem when I turned on http2. I then turned it off but kept https configured and that worked. At this point I'm thinking that the issue is http2, not https itself.

The only difference from when I ran the tests only with http is that I used the environment variable `NODE_EXTRA_CA_CERTS=...` to point to the self-signed certificate I created for testing.

I also used the `.ca` call provided through superagent, and that worked after I turned off http2, but I would have had to add it to all tests. `NODE_EXTRA_CA_CERTS=` take care of the whole test suite in one fell swoop.

**Comment by crystalfp** [comment]
Unfortunately, defining `NODE_EXTRA_CA_CERTS` before tests changes nothing. All tests fail with `socket hang up` as before.

**Comment by crystalfp** [comment]
Dear @lddubeau,
could you share your code? I'm lost on how to turn off http2 maintaining https.
My real code is like the one I posted. Simply based on a variable `useHTTP2` I run the code above or a code running http. If someone thinks it is relevant, I could post a minimal example.
Thanks!
mario

**Comment by lamweili** [comment]
Given the date of this issue, it should be `supertest@<=5.0.0-0`.
Back then, `http2` wasn't supported by `supertest`.

---

Nevertheless, this http2 feature has been incorporated into `supertest@6.3.0`.
A sample code snippet is in the [`README.md`](https://github.com/visionmedia/supertest/blob/6a950434e26f2df25f1c6d08682dbae14a198aeb/README.md).

Based on your code, I would reckon it would be something like:
```js
const request = require('supertest');

const options = {
  key:  fs.readFileSync(path.join(__dirname, "cert", "privkey.pem")),
  cert: fs.readFileSync(path.join(__dirname, "cert", "cert.pem"))
};
const app = function(req, res) {
  res.end('hey');
};
const server = http2.createSecureServer(options, app);
```

```js
// either
request(server)       // pass in your http2 server
  .get('/')
  .http2()            // https://visionmedia.github.io/superagent/#using-http/2
  .disableTLSCerts(); // https://visionmedia.github.io/superagent/#tls-options

// or
request(server)       // pass in your http2 server
  .get('/')
  .http2()            // https://visionmedia.github.io/superagent/#using-http/2
  .trustLocalhost();  // https://visionmedia.github.io/superagent/#testing-on-localhost
```
