### ISSUE TITLE
Supertest converts number query params to string

### ISSUE THREAD

**Issue by theseeker16** [visionmedia/supertest#622]
Hello, I'm having an issue with supertest when I send a number param by query. The server catches the params as string.

PD: I've got a transform in the DTO to convert any string value into a number.  

this is my test
```
it('should retrieve all the template with the params the limit,page', async (done) => {
    // Arrange
    let params = {
      limit: 10,
      page: 1
    }

    // Act
    const response = await supertest(app.getHttpServer())
      .get("/email/get")
      .set('Content-Type', 'application/json;charset=utf-8')
      .set("Content-Lenght", '51')
      .set('Authorization', 'bearer ' + globalToken)
      .query({ limit: params.limit, page: params.page })
  });
```

Any help ?

**Comment by jonathansamines** [comment]
@theseeker16 Could you provide an isolated reproduction for me to check? Otherwise, would be really hard to understand what is going on.

**Comment by theseeker16** [comment]
@jonathansamines Maybe I'll do it in these days. It's complicated because I'm using NestJS and rabbitMQ in a microservices architecture. Of course, I'm doing these tests in a REST microservice who connects them with the rabbitMQ layer.

**Comment by YoliTerco** [comment]
Pudiste corregir eso de los parámetros?
También tengo el mismo problema envió un valor numérico y lo  convierte en cadena........

`/api/usuarios/Update/:${UsuariosMock[0].id}`

**Comment by theseeker16** [comment]
@YoliTerco no, at this moment it has the same behavior.

**Comment by theseeker16** [comment]
@jonathansamines here it's a simple project using nest js, it contains the tests, just run npm run test:e2e, I let a console.log with the type of the variable for the request, please let me know if it's my mistake. Thank you

**Comment by jonathansamines** [comment]
@theseeker16 After researching a bit about nest, looks like they do not parse any input value on purpose. Nest documentation suggest using a transformation pipe: https://docs.nestjs.com/pipes#transformation-use-case

I have never user nest, so it is hard to tell if that is what is actually happening. However, I did try the provided reproduction and could reproduce the issue even without supertest being involved (directly hitting the endpoint from my browser)

Hope the above information helps.

**Comment by AustinGil** [comment]
Jumping in here for another opinion, but I thought query params were always parsed as strings and it's up to you to convert them in your route handlers.

**Comment by swkim0572** [comment]
I use moleculerJs
Numbers are converted to string

**Comment by niftylettuce** [comment]
Querystring is a string.  Your server code should parse keys in the querystring that should be converted to numbers manually.
