### ISSUE TITLE
Is there a way to partially match response bodies?

### ISSUE THREAD

**Issue by mandreyel** [visionmedia/supertest#628]
Apologies if this was documented somewhere, I haven't found it.

It would be very useful, I think, if it were possible to match only some fields of a response body's properties, or only some elements of an array.

The motivation is that sometimes only a part of the data is known beforehand, so it is cumbersome to write tests for these endpoints, by having to manually look for array elements in the response body in a closure given to `then`.

**Comment by jonathansamines** [comment]
I don't think it is something built-in, but might not be that hard to accomplish from your side using an utility from your assertion library such as chai's [include assertion](https://www.chaijs.com/api/bdd/#method_include)


```js
describe('GET /user', function() {
  it('responds with json', function(done) {
    request(app)
      .get('/user')
      .expect((res) => expect(res.body).to.deep.include(subsetOfProperties))
      .end(done);
  });
});
```

**Comment by mandreyel** [comment]
Oh that's really helpful, thanks @jonathansamines!

Closed since I can now see this is not the job of supertest but rather that of the assertion library.

**Comment by davelopware-davea** [comment]
Found this from googling. If you're using **jest** rather than chai, you can tweak @jonathansamines 's code as follows:

```typescript
describe('GET /user', function() {
  it('responds with json', function(done) {
    request(app)
      .get('/user')
      .expect((res) => expect(res.body).toEqual(expect.objectContaining(subsetOfProperties)))
      .end(done);
  });
});
```

**Comment by tdislay** [comment]
To complement @davelopware-davea's comment, you can directly create a custom function that you add in the prototype of supertest's `Test` class (using Jest, Mocha or Vitest):
```ts
import { Test } from "supertest";

// Typescript supertest's module extension
declare module "supertest" {
  interface Test {
    expectPartial: (errorCode: number, body: object) => Test;
  }
}

(Test.prototype as Test).expectPartial = function (statusCode: number, body: object) {
  this._asserts.push((res: Response) => this._assertStatus(statusCode, res));
  this._asserts.push((res: Response) => expect(res.body).toMatchObject(body));

  return this;
}
```
You also may want to add some `// @ts-ignore`s or some type casting to ignore ts errors about you accessing Test's private methods (`_assertStatus`, `_asserts`).
This file needs to be imported for each tests (e.g. using the `setupFiles` property in your testing framework config file).

---
Also, in reality, for DX I used the `wrapAssertFn` function (which I arranged to be typescript friendly) from [here](https://github.com/ladjs/supertest/blob/master/lib/test.js#L301).
```ts
function wrapAssertFn(
  assertFn: (res: Response) => void | Error
): (res: Response) => void | Error {
  const savedStack = new Error().stack!.split("\n").slice(3);

  return function (res: Response) {
    let badStack;
    let err: void | Error;
    try {
      err = assertFn(res);
    } catch (e) {
      err = e as Error;
    }
    if (err instanceof Error && err.stack != null) {
      badStack = err.stack.replace(err.message, "").split("\n").slice(1);
      err.stack = [err.toString()]
        .concat(savedStack)
        .concat("----")
        .concat(badStack)
        .join("\n");
    }
    return err;
  };
}
```

Then you just have to wrap your assertion functions in it:
```ts
this._asserts.push(wrapAssertFn((res: Response) => this._assertStatus(statusCode, res)));
```
