### ISSUE TITLE
Response status assertion doesn't work properly in peculiar cases

### ISSUE THREAD

**Issue by viswanathkgp12** [visionmedia/supertest#629]
I am using supertest and for some reason, the response `status code` assertion doesn't work properly.

```
const express = require("express");

const request = require("supertest");

describe("sample test", () => {
  it("correctly identifies the response status as incorrect", function(done) {
    const app = express();

    app.get("/", function(req, res) {
      res.status(404).send("hey");
    });

    request(app)
      .get("/")
      .expect(200, done);
  });

  it("fails to stop execution at the status code check itself and proceeds further", function(done) {
    const app = express();

    app.get("/", function(req, res) {
      res.status(404).send("hey");
    });

    request(app)
      .get("/")
      .expect(200)
      .end(function(err, res) {
        done();
      });
  });
});
```

Here in the second test case, even though the status is clearly 404(also confirmed via console.log), code execution assertion doesn't break at `expect(200)` and continues for other validations on response body/err.

**Results**
**_Actual_**

  sample test
    1) correctly identifies the response status as incorrect
    ✓ fails to stop execution at the status code check itself and proceeds further

  1 passing (68ms)
  1 failing

  1) sample test
       correctly identifies the response status as incorrect:
     Error: expected 200 "OK", got 404 "Not Found"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1618:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**_Expected_**
Both the test cases should fail regardless

**Comment by jonathansamines** [comment]
@viswanathkgp12 I think that is part of supertest design. From it's documentation:

> If you are using the .end() method .expect() assertions that fail will not throw - they will return the assertion as an error to the .end() callback. In order to fail the test case, you will need to rethrow or pass err to done(), as follows:

That is stated mostly at the end of the example section: https://github.com/visionmedia/supertest#example

**Comment by viswanathkgp12** [comment]
Ohh...I missed that part. Thanks
