### ISSUE TITLE
How to get response time for each request? 

### ISSUE THREAD

**Issue by muthukumarsivajothi** [visionmedia/supertest#637]
For status i can make use of .status which provides 200, 400, 404. Is there any similar methods i can make use of (i.e something like .time will provide me 300ms, 400ms)

**Comment by TimDaub** [comment]
#261 duplicate. But wasn't addressed unfortunately.

**Comment by niftylettuce** [comment]
This adds a `X-Response-Header` https://www.npmjs.com/package/response-time
