### ISSUE TITLE
Should expect(400) but expect(200) works instead !!

### ISSUE THREAD

**Issue by sampathkatari** [visionmedia/supertest#650]
For reference i wrote a sample app demonstrating the issue here: https://github.com/sampathkatari/supertest-example

If you look at the test file in __tests__ folder and look at the below test case
```
it('Get user record which does not exists', (done) => {
        const expectedResponse = {
            message: 'No user found with given ID'
        }
        request(app)
        .get('/user/2')
        .expect(200) //This is supposed to be 400
        .end((err, res) => {
            expect(res.body).toEqual(expectedResponse)
            done();
        })
    })
```

and also if you look at the actual api

```
app.get('/user/:id', (req, res) => {
    const userById = users.find(user => user.id === req.params.id);
    if(userById) {
        res.send(userById)
    } else {
        res.status(400).send({
            message: 'No user found with given ID'
        })
    }
})
```

Here i have been sending a response with status 400 but expect(200) works with supertest?

What could be the issue? Am i doing something wrong or is something wrong in the library? Need help on this !!

**Comment by jonathansamines** [comment]
@sampathkatari When using the `.end()` callback, you are responsible for forwarding the supertest error to the test runner. In this case, you could have to call `done` with the `.end((err))` if any.

**Comment by sampathkatari** [comment]
Got it! Thanks. 👍
