### ISSUE TITLE
superagent HTTP method defined as string not working

### ISSUE THREAD

**Issue by renderorange** [visionmedia/supertest#662]
In the supertest documentation it says, `Anything you can do with superagent, you can do with supertest`.  Then reading the documentation for superagent it shows how the `HTTP method may also be passed as a string`.

```
request('GET', '/search').then(success, failure);
```

However, I can't seem to get it to work, always getting back `TypeError: agent is not a function`.

Below is a small example highlighting what I'm trying to do in my test.

```
'use strict';

const app = require( './../server' );
const supertest = require( 'supertest' );
const assert = require( 'assert' );
const agent = supertest.agent( app );

let status = 200;
let route = 'accessories';
let method = 'get';

describe( 'test known things', function () {
    it( 'returns ' + status, function ( done ) {
        agent( method, '/' + route )
            .then( function( res ) {
                assert.strictEqual( res.status, status );
                done();
            })
            .catch( function( err ) {
                done( err );
            });
    });
});
```

If I switch out the method as string for the chained method, it works, but need to be able to call method as string for the way I'm building the test.  Is there something I'm missing from the documentation, or is the method as string something that's no longer supported?

Thanks.

**Comment by Scotsoo** [comment]
You can do the following: 
Access the agent with an indexed key `agent[method]`. Should be able to achieve the result you're after.
```
'use strict';

const app = require( './../server' );
const supertest = require( 'supertest' );
const assert = require( 'assert' );
const agent = supertest.agent( app );

let status = 200;
let route = 'accessories';
let method = 'get';

describe( 'test known things', function () {
    it( 'returns ' + status, function ( done ) {
        agent[method]('/' + route )
            .then( function( res ) {
                assert.strictEqual( res.status, status );
                done();
            })
            .catch( function( err ) {
                done( err );
            });
    });
});
```
