### ISSUE TITLE
What changed between v4 and v5?

### ISSUE THREAD

**Issue by peterjuras** [visionmedia/supertest#676]
Hi,

I wanted to ask whether there have been any changes or breaking changes in v5.0.0.
The [release notes](https://github.com/visionmedia/supertest/releases/tag/v5.0.0) do not mention any changes.

I saw in some commit that tests are now run using the calling node version, but I'm not sure if there are any other changes.

Best regards,
Peter

**Comment by rimiti** [comment]
You can check changes on this link: https://github.com/visionmedia/supertest/compare/v5.0.0-0...v5.0.0

The most important change is the (major) update of superagent.

**Comment by peterjuras** [comment]
Thanks for the quick response.

Even when looking at the changes in your link, or on the release notes from superagent it is not clear which breaking changes were made, or even if any breaking change was made.

Since there are more than 430.000 repositories using superagent and over 300.000 repos using supertest adding detailed changelogs would be helpful to users out there.

**Comment by chris-williams-efr** [comment]
Please.. when moving major versions the first thing we have to do is to read through the changelog, to see what's gone on..  we need something to know what to expect please
