### ISSUE TITLE
cannot connect to db

### ISSUE THREAD

**Issue by marcosdipaolo** [visionmedia/supertest#680]
Hi, my app is using a dockerized db which exposes port 3306 to the outside world, so it's basically the same as mysql installed locally as a service.

My API is connecting with no problems to the database. It uses thus data:
```env
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=root
```
but when passing the app to supertest and making a request i get:
```
"Access denied for user 'root'@'172.17.0.1' (using password: NO)"
```
i wonder why it isn't connecting to the db as the app does?

It's an node api built with node, express and sequelize

**Comment by marcosdipaolo** [comment]
I was not aware that jest sets the `NODE_ENV` variable even if you have it set in the `.env` file

**Comment by bilalesi** [comment]
can you exaplain the solution, i am facing the same issue !!
