### ISSUE TITLE
Where is the Changelog or release-notes for last 2 major versions

### ISSUE THREAD

**Issue by ryami333** [visionmedia/supertest#683]
Hi there, my project's version of `supertest` is currently 2 major versions behind the latest, but I'm afraid of upgrading because there are no release notes or Changelog which document the breaking changes which necessitated a major release.

**Comment by johnk1** [comment]
Does https://github.com/visionmedia/supertest/releases help?

**Comment by niftylettuce** [comment]
Yes please use https://github.com/visionmedia/supertest/releases moving forwards

**Comment by ryami333** [comment]
No @niftylettuce and @johnk1 it doesn't. Those are just a list of the addressed issues and merged pull requests - those notes do not give justification for the new major release and state the breaking changes.

**Comment by ryami333** [comment]
Another month down the track and I still don't know if it's safe to upgrade two major versions because there are no release notes beyond a list of PRs/commits. The releases page which you've linked to _demonstrates_ my issue, it does not resolve it. So, let me be more direct:

1. What parts of this library's API contained breaking changes between releases 4.X.X and 5.X.X and 6.X.X, respectively?
2. What mechanism do you plan on using in the future for documenting such breaking changes?
