### ISSUE TITLE
Error: connect EADDRNOTAVAIL on Windows

### ISSUE THREAD

**Issue by wclr** [visionmedia/supertest#7]
Node 8.0.2
Error: connect EADDRNOTAVAIL
 at errnoException (net.js:776:11)
 at Object.afterConnect [as oncomplete](net.js:767:19)

workaround:
supertest/lib/test.js

function Test line 43 setting this.url

replace 0.0.0.0 address with 127.0.0.1

What can be the problem with 0.0.0.0?

**Comment by barbalex** [comment]
I have the exact same problem on windows 10:

    const server = supertest.agent('http://0.0.0.0:4001')

returns `Uncaught Error: connect EADDRNOTAVAIL 0.0.0.0:4001`

    const server = supertest.agent('http://localhost:4001')

works
