### ISSUE TITLE
Got TypeError flat is not a function on Node.js 10  supertest 6.1.1

### ISSUE THREAD

**Issue by ktutnik** [visionmedia/supertest#702]
Look like this update 02888268617e546fb087629ac773b207fc164bdd which uses `Array.flat` doesn't work in older Node.js 

So when a test doesn't pass, instead of showing proper error stack, its showing inappropriate error like this

```
TypeError: [err.toString(...),savedStack,"----",badStack].flat is not a function
```

**Comment by therealklanni** [comment]
Bug introduced by [this commit](https://github.com/visionmedia/supertest/commit/d41d10b7a8ce2590e38857362930354b648bf26f) from #690

**Comment by niftylettuce** [comment]
v6.1.2 released https://github.com/visionmedia/supertest/releases/tag/v6.1.2
