### ISSUE TITLE
[Help] instanceof doesnt working with supertest

### ISSUE THREAD

**Issue by murilohns** [visionmedia/supertest#722]
# Context

I have an error handler middleware, that is responsible to normalize error messages. if the error isn't a normalized error, it throws an internal server error. like that:

```js
const errorHandlerMiddleware = (
  error: Error,
  _request: Request,
  response: Response,
  _next: NextFunction,
) => {
  const normalizedError =
    error instanceof APIBaseError ? error : new InternalServerError();

  logger.error({
    name: normalizedError.name,
    message: error.message,
    error: normalizedError,
    stack: normalizedError.stack,
  });

  return response
    .status(normalizedError.statusCode)
    .json(normalizedError.toResponse());
};
```

locally, it works fine, like the image below:
![image](https://user-images.githubusercontent.com/18074134/121462904-afac3a80-c987-11eb-8d77-f247f29a2863.png)

But using supertest, the instanceof isn't working 🤔 

```js
  console.log({
    name: error.name,
    message: error.message,
    isInstanceOf: error instanceof APIBaseError,
  });
```

![image](https://user-images.githubusercontent.com/18074134/121463908-462d2b80-c989-11eb-8019-a1939e54edc0.png)

# Setup

I'm using TypeScript, running in docker-compose using "babel-node":
```js
"start": "nodemon ./src/infra/http/server.ts --exec babel-node --extensions '.js,.ts' --inspect=0.0.0.0:9229 --nolazy",
```

**Comment by murilohns** [comment]
Solved! Its a `tsconfig` problem!

**Comment by TobiTenno** [comment]
what exactly is the tsconfig issue and how did you solve it?
