### ISSUE TITLE
Test failing when checking response body for array

### ISSUE THREAD

**Issue by ollyrowe** [visionmedia/supertest#734]
I found a potential issue within `v1.6.4` when checking that a response body resolves to an array.

I have the following jest test which is failing:

```js
it(`GET todos`, async () => {
  return request(app.getHttpServer())
    .get('/todos')
    .set('Authorization', `Bearer ${accessToken}`)
    .expect(200)
    .expect(await todoService.findAll());
});
```
Note that `await todoService.findAll()` returns an array.

This test produces the following error:

```
expected one of "[object Object]", got 200 "OK"
```

Reverting the supertest package version back to `v1.6.3` fixes the issue and the test passes as expected.

**Comment by niftylettuce** [comment]
see https://github.com/visionmedia/supertest/pull/728#issuecomment-896998201
