### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by efcjunior** [visionmedia/supertest#739]
`const request = require('supertest');

describe('Hello World Jest Package', () => {

    est('Is Test name Hello World', () => {

        request = request('http://localhost:5555');

        request.get('/').expect(200, function(err){
            console.log(err);
        });       
    });
});`

**Comment by niftylettuce** [comment]
Your usage should instead be:

```diff
-    request = request('http://localhost:5555');
+    const req = request('http://localhost:5555');

    request.get('/').expect(200, function(err){
        console.log(err);
    });       
```

You cannot redefine a `const` variable, you should use `let` instead, but your usage should actually be as per the diff I shared.
