### ISSUE TITLE
Update superagent dependency to 7.0.0

### ISSUE THREAD

**Issue by niekraaijmakers** [visionmedia/supertest#750]
I'd like to suggest a version bump to 7.0.0+ of superagent.

It contains a fix for this issue:

https://github.com/visionmedia/superagent/issues/1609#issuecomment-1008501423

Which prevents us from using this library.
Would this be possible? Thanks!

**Comment by niftylettuce** [comment]
Released <https://github.com/visionmedia/supertest/releases/tag/v6.2.0>
