### ISSUE TITLE
Clear cookies between requests

### ISSUE THREAD

**Issue by DeaconDesperado** [visionmedia/supertest#83]
I have some mocha tests using supertest and I've run into a case where independent tests (separate test files) are not re-initing the agent and start out in another test with the same cookie jar from the last.

I'm assuming this is because of the run-once nature of `require`, and that I'm getting one singleton agent instance (I think I more or less verified this looking at the source.)  Is there a way I can clear the cookiejar in the `beforeEach` call in mocha?

Thanks!

**Comment by seonixx** [comment]
Did anyone ever find a solution for this? I've been using set('Cookie', []) on the required requests but am hoping there is a more elegant solution.

**Comment by sleelily** [comment]
I find that the instance of supertest created by`require('supertest').agent(server)`will persist cookie between unit test. `require('supertest')(server)`will not.
